In [1]:
# Python 2 imports 
from __future__ import print_function, division 

import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt
import os

pd.set_option("display.max_columns", 30)
pd.set_option("display.max_colwidth", 100)
pd.set_option("display.precision", 3)

plt.style.use('ggplot')
%matplotlib inline

In [2]:
CSV_PATH = r"../Datasets/magic.csv"
print(os.path.abspath(CSV_PATH))

/Users/palance/Documents/GitHub/Python-Machine-Learning-Blueprints/Datasets/magic.csv

In [3]:
df = pd.read_csv(CSV_PATH)

In [4]:
df.columns

Index(['routablemask_link', 'routablemask_link/_text',
       'routablemask_link/_title', 'routablemask_link_numbers',
       'routablemask_content', 'imagebadge_value', 'imagebadge_value_numbers',
       'routable_link', 'routable_link/_text', 'routable_link/_title',
       'routable_link_numbers', 'listingtype_value', 'pricelarge_value',
       'pricelarge_value_prices', 'propertyinfo_value',
       'propertyinfo_value_numbers', 'fineprint_value',
       'fineprint_value_numbers', 'tozcount_number', 'tozfresh_value',
       'tablegrouped_values', 'tablegrouped_values_prices', '_PAGE_NUMBER'],
      dtype='object')

In [5]:
df.T  # 转置

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,...,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499
routablemask_link,"http://www.zillow.com/b/2-Ellwood-St-New-York-NY/40.85899,-73.92814_ll/","http://www.zillow.com/b/603-W-140th-St-New-York-NY/40.82376,-73.95335_ll/",http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,"http://www.zillow.com/b/159-Prince-St-New-York-NY/40.72612,-74.00114_ll/",http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,"http://www.zillow.com/b/580-St-Nicholas-Ave-New-York-NY/40.81996,-73.94624_ll/","http://www.zillow.com/b/315-W-21st-St-New-York-NY/40.74427,-73.99991_ll/",http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,"http://www.zillow.com/b/417-E-82nd-St-New-York-NY/40.77406,-73.9501_ll/",...,http://www.zillow.com/homedetails/319-E-53rd-St-APT-2B-New-York-NY-10022/2104750345_zpid/,http://www.zillow.com/homedetails/53-Irving-Pl-APT-3K-New-York-NY-10003/2103128441_zpid/,http://www.zillow.com/homedetails/25-E-67th-St-APT-8D-New-York-NY-10065/2100777265_zpid/,"http://www.zillow.com/b/209-W-102nd-St-New-York-NY/40.79841,-73.96825_ll/","http://www.zillow.com/b/171-E-84th-St-New-York-NY/40.777797,-73.95494_ll/",http://www.zillow.com/homedetails/303-E-73rd-St-E-New-York-NY-10021/2100777278_zpid/,"http://www.zillow.com/b/233-E-77th-St-New-York-NY/40.77267,-73.95695_ll/",http://www.zillow.com/homedetails/422-E-81st-St-APT-4A-New-York-NY-10028/2111603077_zpid/,"http://www.zillow.com/b/9-E-118th-St-New-York-NY/40.80185,-73.94463_ll/","http://www.zillow.com/b/160-W-71st-St-New-York-NY/40.77736,-73.98091_ll/","http://www.zillow.com/b/562-W-End-Ave-New-York-NY/40.78965,-73.97688_ll/",http://www.zillow.com/homedetails/445-W-49th-St-APT-3B-New-York-NY-10019/2106388119_zpid/,http://www.zillow.com/homedetails/203-E-121st-St-APT-901-New-York-NY-10035/2100777283_zpid/,"http://www.zillow.com/b/325-E-48th-St-New-York-NY/40.7533,-73.96807_ll/",http://www.zillow.com/homedetails/434-E-72nd-St-APT-2C-New-York-NY-10021/2120058527_zpid/
routablemask_link/_text,5 photos,10 photos,NaN,9 photos,5 photos,7 photos,3 photos,NaN,7 photos,1 photo,NaN,9 photos,4 photos,6 photos,3 photos,...,5 photos,6 photos,NaN,7 photos,5 photos,5 photos,5 photos,4 photos,7 photos,1 photo,NaN,4 photos,4 photos,4 photos,1 photo
routablemask_link/_title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
routablemask_link_numbers,5,10,NaN,9,5,7,3,NaN,7,1,NaN,9,4,6,3,...,5,6,NaN,7,5,5,5,4,7,1,NaN,4,4,4,1
routablemask_content,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
imagebadge_value,5 photos,10 photos,NaN,9 photos,5 photos,7 photos,3 photos,NaN,7 photos,1 photo,NaN,9 photos,4 photos,6 photos,3 photos,...,5 photos,6 photos,NaN,7 photos,5 photos,5 photos,5 photos,4 photos,7 photos,1 photo,NaN,4 photos,4 photos,4 photos,1 photo
imagebadge_value_numbers,5,10,NaN,9,5,7,3,NaN,7,1,NaN,9,4,6,3,...,5,6,NaN,7,5,5,5,4,7,1,NaN,4,4,4,1
routable_link,"http://www.zillow.com/b/2-Ellwood-St-New-York-NY/40.85899,-73.92814_ll/","http://www.zillow.com/b/603-W-140th-St-New-York-NY/40.82376,-73.95335_ll/",http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,"http://www.zillow.com/b/159-Prince-St-New-York-NY/40.72612,-74.00114_ll/",http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,"http://www.zillow.com/b/580-St-Nicholas-Ave-New-York-NY/40.81996,-73.94624_ll/","http://www.zillow.com/b/315-W-21st-St-New-York-NY/40.74427,-73.99991_ll/",http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,"http://www.zillow.com/b/417-E-82nd-St-New-York-NY/40.77406,-73.9501_ll/",...,http://www.zillow.com/homedetails/319-E-53rd-St-APT-2B-New-York-NY-10022/2104750345_zpid/,http://www.zillow.com/homedetails/53-Irving-Pl-APT-3K-New-York-NY-10003/2103128441_zpid/,http://www.zillow.com/homedetails/25-E-67th-St-APT-8D-New-York-NY-10065/2100777265_zpid/,"http://www.zillow.com/b/209-W-102nd-St-New-York-NY/40.79841,-73.96825_ll/","http://www.zillow.com/b/171-E-84th-St-New-York-NY/40.777797,-73.95494_ll/",http://www.zillow.com/homedetails/303-E-73rd-St-E-New-York-NY-10021/2100777278_zpid/,"http://www.zillow.com/b/233-E-77th-St-New-York-NY/40.77267,-73.95695_ll/",http://www.zillow.com/homedetails/422-E-81st-St-APT-4A-New-York-NY-10028/2111603077_zpid/,"http://www.zillow.com/b/9-E-118th-St-New-York-NY/40.80185,-73.94463_ll/","http://www.zillow.com/b/160-W-71st-St-New-York-NY/40.77736,-73.98091_ll/","http://www.zillow.com/b/562-W-End-Ave-New-York-NY/40.78965,-73.97688_ll/",http://www.zillow.com/homedetails/445-W-49th-St-APT-3B-New-York-NY-10019/2106388119_zpid/,http://www.zillow.com/homedetails/203-E-121st-St-APT-901-New-York-NY-10035/2100777283_zpid/,"http://www.zillow.com/b/325-E-48th-St-New-York-NY/40.7533,-73.96807_ll/",http://www.zillow.com/homedetails/434-E-72nd-St-APT-2C-New-York-NY-10021/2120058527_zpid/
routable_link/_text,2 Ellwood St,603 W 140th St,"9 E 129th St # 1, New York, NY10035","710 Riverside Dr APT 2C, New York, NY10031","413 E 84th St APT 8, New York, NY10028","324 Pleasant Ave APT 6E, New York, NY10035",159 Prince St,"217 Thompson St APT 6, New York, NY10012",580 St Nicholas Ave,315 W 21st St,"340 W 47th St APT 4C, New York, NY10036","1356 1st Ave APT 5B, New York, NY10021","101 W 77th St APT 3C, New York, NY10024","111 W 74th St APT 2R, New York, NY10023",417 E 82nd St,...,"319 E 53rd St APT 2B, New York, NY10022","53 Irving Pl APT 3K, New York, NY10003","25 E 67th St APT 8D, New York, NY10065",209 W 102nd St,171 E 84th St,"303 E 73rd St # E, New York, NY10021",233 E 77th St,"422 E 81st St APT 4A, New York, NY10028",9 E 118th St,160 W 71st St,562 W End Ave,"445 W 49th St APT 3B, New York, NY10019","203 E 121st St APT 901, New York, NY10035",325 E 48th St,"434 E 72nd St APT 2C, New York, NY10021"
routable_link/_title,"2 Ellwood St APT 5H, New York, NY Real Estate","603 W 140th St APT 44, New York, NY Real Estate","9 E 129th St # 1, New York, NY Real Estate","710 Riverside Dr APT 2C, New York, NY Real Estate","413 E 84th St APT 8, New York, NY Real Estate","324 Pleasant Ave APT 6E, New York, NY Real Estate","159 Prince St APT 2, New York, NY Real Estate","217 Thompson St APT 6, New York, NY Real Estate","580 St Nicholas Ave APT 1M, New York, NY Real Estate","315 W 21st St APT 2C, New York, NY Real Estate","340 W 47th St APT 4C, New York, NY Real Estate","1356 1st Ave APT 5B, New York, NY Real Estate","101 W 77th St APT 3C, New York, NY Real Estate","111 W 74th St APT 2R, New York, NY Real Estate","417 E 82nd St APT 4C, New York, NY Real Estate",...,"319 E 53rd St APT 2B, New York, NY Real Estate","53 Irving Pl APT 3K, New York, NY Real Estate","25 E 67th St APT 8D, New York, NY Real Estate","209 W 102nd St # 3R, New York, NY Real Estate","171 E 84th St APT 19E, New York, NY Real Estate","303 E 73rd St # E, New York, NY Real Estate","233 E 77th St # 1, New York, NY Real Estate","422 E 81st St APT 4A, New York, NY Real Estate","9 E 118th St APT A, New York, NY Real Estate","160 W 71st St APT 14B, New York, NY Real Estate","562 W End Ave APT 7D, New York, NY Real Estate","445 W 49th St APT 3B, New York, NY Real Estate","203 E 121st St APT 901, New York, NY Real Estate","325 E 48th St # 22, New York, NY Real Estate","434 E 72nd St APT 2C, New York, NY Real Estate"
routable_link_numbers,2,603; 140,9; 129; 1,710; 2,413; 84; 8,324; 6,159,217; 6,580,315; 21,340; 47; 4,1356; 1; 5,101; 77; 3,111; 74; 2,417; 82,...,319; 53; 2,53; 3,25; 67; 8,209; 102,171; 84,303; 73,233; 77,422; 81; 4,9; 118,160; 71,562,445; 49; 3,203; 121; 901,325; 48,434; 72; 2
listingtype_value,Apartments For Rent,Apartments For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartments For Rent,Apartment For Rent,Apartments For Rent,Apartments For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartments For Rent,...,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartments For Rent,Apartments For Rent,Apartment For Rent,Apartments For Rent,Apartment For Rent,Apartments For Rent,Apartments For Rent,Apartments For Rent,Apartment For Rent,Apartment For Rent,Apartments For Rent,Apartment For Rent
pricelarge_value,NaN,NaN,"$1,750/mo","$3,000/mo","$2,300/mo","$2,500/mo",NaN,"$2,800/mo",NaN,NaN,"$2,490/mo","$2,750/mo","$2,150/mo","$2,875/mo",NaN,...,"$2,170/mo","$2,300/mo","$2,600/mo",NaN,NaN,"$2,265/mo",NaN,"$2,150/mo",NaN,NaN,NaN,"$2,195/mo","$1,795/mo",NaN,"$2,150/mo"
pricelarge_value_prices,NaN,NaN,1.75e+03,3e+03,2.3e+03,2.5e+03,NaN,2.8e+03,NaN,NaN,2.49e+03,2.75e+03,2.15e+03,2.88e+03,NaN,...,2.17e+03,2.3e+03,2.6e+03,NaN,NaN,2.26e+03,NaN,2.15e+03,NaN,NaN,NaN,2.2e+03,1.8e+03,NaN,2.15e+03
propertyinfo_value,"2 Ellwood St, New York, NY","603 W 140th St, New York, NY",1 bd • 1 ba,"2 bds • 2 ba • 1,016 sqft",Studio • 1 ba,2 bds • 1 ba,"159 Prince St, New York, NY",2 bds • 1 ba,"580 St Nicholas Ave, New York, NY","315 W 21st St, New York, NY",1 bd • 1 ba,"1 bd • 1 ba • 496 sqft • 4,502 sqft lot • Built 1900",Studio • 1 ba,1 bd • 1 ba,"417 E 82nd St, New York, NY",...,Studio • 1 ba,Studio • 1 ba • 400 sqft,Studio • 1 ba,"209 W 102nd St, New York, NY","171 E 84th St, New York, NY",1 bd • 1 ba,"233 E 77th St, New York, NY",1 bd • 1 ba,"9 E 118th St, New York, NY","160 W 71st St, New York, NY","562 W End Ave, New York, NY",Studio • 1 ba,Studio • 1 ba • 550 sqft,"325 E 48th St, New York, NY",1 bd • 1 ba
propertyinfo_value_numbers,2,603; 140,1; 1,2; 2; 1016,1,2; 1,159,2; 1,580,315; 21,1; 1,1; 1; 496; 4502; 1900,1,1; 1,417; 82,...,1,1; 400,1,209; 102,171; 84,1; 1,233; 77,1; 1,9; 118,160; 71,562,1,1; 550,325; 48,1; 1
fineprint_value,6 matching units,2 matching units,NaN,NaN,NaN,NaN,4 matching units,NaN,3 matching units,2 matching units,NaN,NaN,NaN,NaN,3 matching units,...,NaN,NaN,NaN,2 matching units,2 matching units,NaN,3 matching units,NaN,4 matching units,3 matching units,3 matching units,NaN,NaN,2 matching units,NaN
fineprint_value_numbers,6,2,NaN,NaN,NaN,NaN,4,NaN,3,2,NaN,NaN,NaN,NaN,3,...,NaN,NaN,NaN,2,2,NaN,3,NaN,4,3,3,NaN,NaN,2,NaN
tozcount_number,NaN,NaN,48,1,2,2,NaN,3,NaN,NaN,6,6,6,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tozfresh_value,Updated today,Updated today,minutes ago,hour ago,hours ago,hours ago,Updated today,hours ago,Updated today,Updated today,hours ago,hours ago,hours ago,hours ago,Updated today,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tablegrouped_values,"1 Bedrooms $1,500+ 1.0 ba -- sqft; 2 Bedrooms $1,750+ 1.0 ba -- sqft","1 Bedrooms $2,100 1.0 ba 800 sqft; 2 Bedrooms $2,595 1.0 ba 1,000 sqft",NaN,NaN,NaN,NaN,"1 Bedrooms $2,650+ 1.0 ba -- sqft",NaN,"1 Bedrooms $1,900+ 1.0 ba -- sqft","Studios $2,675+ 1.0 ba -- sqft",NaN,NaN,NaN,NaN,"Studios $2,000+ 1.0 ba -- sqft",...,NaN,NaN,NaN,"2 Bedrooms $2,925+ 1.0 ba -- sqft","Studios $2,800 1.0 ba 621 sqft; 1 Bedrooms $2,850 1.0 ba 636 sqft",NaN,"1 Bedrooms $1,944+ 1.0 ba -- sqft",NaN,"1 Bedrooms $2,150+ 1.0 ba -- sqft; 2 Bedrooms $2,738+ 1.0 ba -- sqft","1 Bedrooms $2,931+ 1.0 ba -- sqft","Studios $2,950 1.0 ba -- sqft; 1 Bedrooms $2,800+ 1.0 ba -- sqft",NaN,NaN,"Studios $2,195+ 1.0 ba -- sqft",NaN
tablegrouped_values_prices,1500; 1750,2100; 2595,NaN,NaN,NaN,NaN,2650,NaN,1900,2675,NaN,NaN,NaN,NaN,2000,...,NaN,NaN,NaN,2925,2800; 2850,NaN,1944,NaN,2150; 2738,2931,2950; 2800,NaN,NaN,2195,NaN
_PAGE_NUMBER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20

In [6]:
# df.T.ix[:,1:2] # 取第1、2列
df.T.loc[:, 1:2] # ix被废弃了，改用loc

,1,2
routablemask_link,"http://www.zillow.com/b/603-W-140th-St-New-York-NY/40.82376,-73.95335_ll/",http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/
routablemask_link/_text,10 photos,NaN
routablemask_link/_title,NaN,NaN
routablemask_link_numbers,10,NaN
routablemask_content,NaN,NaN
imagebadge_value,10 photos,NaN
imagebadge_value_numbers,10,NaN
routable_link,"http://www.zillow.com/b/603-W-140th-St-New-York-NY/40.82376,-73.95335_ll/",http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/
routable_link/_text,603 W 140th St,"9 E 129th St # 1, New York, NY10035"
routable_link/_title,"603 W 140th St APT 44, New York, NY Real Estate","9 E 129th St # 1, New York, NY Real Estate"
routable_link_numbers,603; 140,9; 129; 1
listingtype_value,Apartments For Rent,Apartment For Rent
pricelarge_value,NaN,"$1,750/mo"
pricelarge_value_prices,NaN,1.75e+03
propertyinfo_value,"603 W 140th St, New York, NY",1 bd • 1 ba
propertyinfo_value_numbers,603; 140,1; 1
fineprint_value,2 matching units,NaN
fineprint_value_numbers,2,NaN
tozcount_number,NaN,48
tozfresh_value,Updated today,minutes ago
tablegrouped_values,"1 Bedrooms $2,100 1.0 ba 800 sqft; 2 Bedrooms $2,595 1.0 ba 1,000 sqft",NaN
tablegrouped_values_prices,2100; 2595,NaN
_PAGE_NUMBER,1,1

In [7]:
df['routable_link/_text'].str.contains('203 Rivington')[26:31]

26    False
27    False
28     True
29    False
30    False
Name: routable_link/_text, dtype: bool

In [8]:
df[df['routable_link/_text'].str.contains('203 Rivington')]

,routablemask_link,routablemask_link/_text,routablemask_link/_title,routablemask_link_numbers,routablemask_content,imagebadge_value,imagebadge_value_numbers,routable_link,routable_link/_text,routable_link/_title,routable_link_numbers,listingtype_value,pricelarge_value,pricelarge_value_prices,propertyinfo_value,propertyinfo_value_numbers,fineprint_value,fineprint_value_numbers,tozcount_number,tozfresh_value,tablegrouped_values,tablegrouped_values_prices,_PAGE_NUMBER
28,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",7 photos,NaN,7.0,NaN,7 photos,7.0,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",203 Rivington St,"203 Rivington St APT 5B, New York, NY Real Estate",203,Apartments For Rent,NaN,NaN,"203 Rivington St, New York, NY",203,2 matching units,2.0,NaN,NaN,"1 Bedrooms $3,000 1.0 ba 750 sqft; 2 Bedrooms $3,000 1.0 ba -- sqft",3000; 3000,2
53,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",7 photos,NaN,7.0,NaN,7 photos,7.0,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",203 Rivington St,"203 Rivington St APT 5B, New York, NY Real Estate",203,Apartments For Rent,NaN,NaN,"203 Rivington St, New York, NY",203,2 matching units,2.0,NaN,NaN,"1 Bedrooms $3,000 1.0 ba 750 sqft; 2 Bedrooms $3,000 1.0 ba -- sqft",3000; 3000,3

In [9]:
df['routable_link/_text'].str.contains('280 E 2nd')[26:31]

26    False
27    False
28    False
29    False
30     True
Name: routable_link/_text, dtype: bool

In [10]:
df[df['routable_link/_text'].str.contains('280 E 2nd')]

,routablemask_link,routablemask_link/_text,routablemask_link/_title,routablemask_link_numbers,routablemask_content,imagebadge_value,imagebadge_value_numbers,routable_link,routable_link/_text,routable_link/_title,routable_link_numbers,listingtype_value,pricelarge_value,pricelarge_value_prices,propertyinfo_value,propertyinfo_value_numbers,fineprint_value,fineprint_value_numbers,tozcount_number,tozfresh_value,tablegrouped_values,tablegrouped_values_prices,_PAGE_NUMBER
30,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,"280 E 2nd St # 604, New York, NY10009","280 E 2nd St # 604, New York, NY Real Estate",280; 2; 604,Apartment For Rent,"$2,850/mo",2850.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,2
55,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,"280 E 2nd St # 604, New York, NY10009","280 E 2nd St # 604, New York, NY Real Estate",280; 2; 604,Apartment For Rent,"$2,850/mo",2850.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,3

In [11]:
nn = df[df['routable_link/_text'].str.contains('203 Rivington')|df['routable_link/_text'].str.contains('280 E 2nd')]
nn # 由以上4步的分解可知：它取了指定列包含指定字串的记录

,routablemask_link,routablemask_link/_text,routablemask_link/_title,routablemask_link_numbers,routablemask_content,imagebadge_value,imagebadge_value_numbers,routable_link,routable_link/_text,routable_link/_title,routable_link_numbers,listingtype_value,pricelarge_value,pricelarge_value_prices,propertyinfo_value,propertyinfo_value_numbers,fineprint_value,fineprint_value_numbers,tozcount_number,tozfresh_value,tablegrouped_values,tablegrouped_values_prices,_PAGE_NUMBER
28,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",7 photos,NaN,7.0,NaN,7 photos,7.0,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",203 Rivington St,"203 Rivington St APT 5B, New York, NY Real Estate",203,Apartments For Rent,NaN,NaN,"203 Rivington St, New York, NY",203,2 matching units,2.0,NaN,NaN,"1 Bedrooms $3,000 1.0 ba 750 sqft; 2 Bedrooms $3,000 1.0 ba -- sqft",3000; 3000,2
30,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,"280 E 2nd St # 604, New York, NY10009","280 E 2nd St # 604, New York, NY Real Estate",280; 2; 604,Apartment For Rent,"$2,850/mo",2850.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,2
53,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",7 photos,NaN,7.0,NaN,7 photos,7.0,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",203 Rivington St,"203 Rivington St APT 5B, New York, NY Real Estate",203,Apartments For Rent,NaN,NaN,"203 Rivington St, New York, NY",203,2 matching units,2.0,NaN,NaN,"1 Bedrooms $3,000 1.0 ba 750 sqft; 2 Bedrooms $3,000 1.0 ba -- sqft",3000; 3000,3
55,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,"280 E 2nd St # 604, New York, NY10009","280 E 2nd St # 604, New York, NY Real Estate",280; 2; 604,Apartment For Rent,"$2,850/mo",2850.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,3

In [12]:
nn[:2].T

,28,30
routablemask_link,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/
routablemask_link/_text,7 photos,4 photos
routablemask_link/_title,NaN,NaN
routablemask_link_numbers,7,4
routablemask_content,NaN,NaN
imagebadge_value,7 photos,4 photos
imagebadge_value_numbers,7,4
routable_link,"http://www.zillow.com/b/203-Rivington-St-New-York-NY/40.71825,-73.98307_ll/",http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/
routable_link/_text,203 Rivington St,"280 E 2nd St # 604, New York, NY10009"
routable_link/_title,"203 Rivington St APT 5B, New York, NY Real Estate","280 E 2nd St # 604, New York, NY Real Estate"
routable_link_numbers,203,280; 2; 604
listingtype_value,Apartments For Rent,Apartment For Rent
pricelarge_value,NaN,"$2,850/mo"
pricelarge_value_prices,NaN,2.85e+03
propertyinfo_value,"203 Rivington St, New York, NY",1 bd • 1 ba
propertyinfo_value_numbers,203,1; 1
fineprint_value,2 matching units,NaN
fineprint_value_numbers,2,NaN
tozcount_number,NaN,NaN
tozfresh_value,NaN,NaN
tablegrouped_values,"1 Bedrooms $3,000 1.0 ba 750 sqft; 2 Bedrooms $3,000 1.0 ba -- sqft",NaN
tablegrouped_values_prices,3000; 3000,NaN
_PAGE_NUMBER,2,2

In [13]:
# multiple units
mu = df[df['listingtype_value'].str.contains('Apartments For')] # 多套间房源

In [14]:
# single units
su = df[df['listingtype_value'].str.contains('Apartment For')] # 单套间房源

In [15]:
len(mu)

161

In [16]:
len(su)

339

In [17]:
su.T

,2,3,4,5,7,10,11,12,13,17,18,19,20,21,23,...,470,471,475,477,479,483,484,485,486,487,490,492,496,497,499
routablemask_link,http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,http://www.zillow.com/homedetails/646-10th-Ave-APT-4B-New-York-NY-10036/2114397534_zpid/,http://www.zillow.com/homedetails/76-Carmine-St-APT-4C-New-York-NY-10014/2110813540_zpid/,http://www.zillow.com/homedetails/146-W-120th-St-APT-8-New-York-NY-10027/2100762986_zpid/,http://www.zillow.com/homedetails/137-W-72nd-St-APT-4FE-New-York-NY-10023/2105480982_zpid/,http://www.zillow.com/homedetails/178-Avenue-B-2-New-York-NY-10009/2100763265_zpid/,http://www.zillow.com/homedetails/95-Wall-St-72791-New-York-NY-10005/2103168440_zpid/,...,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/,http://www.zillow.com/homedetails/169-Avenue-A-APT-1-New-York-NY-10009/2105208117_zpid/,http://www.zillow.com/homedetails/722-10th-Ave-APT-3A-New-York-NY-10019/2126268388_zpid/,http://www.zillow.com/homedetails/200-W-70th-St-APT-11L3-New-York-NY-10023/2100774851_zpid/,http://www.zillow.com/homedetails/219-W-78th-St-APT-2F-New-York-NY-10024/2100775303_zpid/,http://www.zillow.com/homedetails/405-W-49th-St-APT-2W-New-York-NY-10019/2100776286_zpid/,http://www.zillow.com/homedetails/230-E-26th-St-APT-3A-New-York-NY-10010/2100776283_zpid/,http://www.zillow.com/homedetails/319-E-53rd-St-APT-2B-New-York-NY-10022/2104750345_zpid/,http://www.zillow.com/homedetails/53-Irving-Pl-APT-3K-New-York-NY-10003/2103128441_zpid/,http://www.zillow.com/homedetails/25-E-67th-St-APT-8D-New-York-NY-10065/2100777265_zpid/,http://www.zillow.com/homedetails/303-E-73rd-St-E-New-York-NY-10021/2100777278_zpid/,http://www.zillow.com/homedetails/422-E-81st-St-APT-4A-New-York-NY-10028/2111603077_zpid/,http://www.zillow.com/homedetails/445-W-49th-St-APT-3B-New-York-NY-10019/2106388119_zpid/,http://www.zillow.com/homedetails/203-E-121st-St-APT-901-New-York-NY-10035/2100777283_zpid/,http://www.zillow.com/homedetails/434-E-72nd-St-APT-2C-New-York-NY-10021/2120058527_zpid/
routablemask_link/_text,NaN,9 photos,5 photos,7 photos,NaN,NaN,9 photos,4 photos,6 photos,NaN,4 photos,6 photos,10 photos,6 photos,17 photos,...,5 photos,8 photos,5 photos,4 photos,6 photos,5 photos,6 photos,5 photos,6 photos,NaN,5 photos,4 photos,4 photos,4 photos,1 photo
routablemask_link/_title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
routablemask_link_numbers,NaN,9,5,7,NaN,NaN,9,4,6,NaN,4,6,10,6,17,...,5,8,5,4,6,5,6,5,6,NaN,5,4,4,4,1
routablemask_content,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
imagebadge_value,NaN,9 photos,5 photos,7 photos,NaN,NaN,9 photos,4 photos,6 photos,NaN,4 photos,6 photos,10 photos,6 photos,17 photos,...,5 photos,8 photos,5 photos,4 photos,6 photos,5 photos,6 photos,5 photos,6 photos,NaN,5 photos,4 photos,4 photos,4 photos,1 photo
imagebadge_value_numbers,NaN,9,5,7,NaN,NaN,9,4,6,NaN,4,6,10,6,17,...,5,8,5,4,6,5,6,5,6,NaN,5,4,4,4,1
routable_link,http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,http://www.zillow.com/homedetails/646-10th-Ave-APT-4B-New-York-NY-10036/2114397534_zpid/,http://www.zillow.com/homedetails/76-Carmine-St-APT-4C-New-York-NY-10014/2110813540_zpid/,http://www.zillow.com/homedetails/146-W-120th-St-APT-8-New-York-NY-10027/2100762986_zpid/,http://www.zillow.com/homedetails/137-W-72nd-St-APT-4FE-New-York-NY-10023/2105480982_zpid/,http://www.zillow.com/homedetails/178-Avenue-B-2-New-York-NY-10009/2100763265_zpid/,http://www.zillow.com/homedetails/95-Wall-St-72791-New-York-NY-10005/2103168440_zpid/,...,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/,http://www.zillow.com/homedetails/169-Avenue-A-APT-1-New-York-NY-10009/2105208117_zpid/,http://www.zillow.com/homedetails/722-10th-Ave-APT-3A-New-York-NY-10019/2126268388_zpid/,http://www.zillow.com/homedetails/200-W-70th-St-APT-11L3-New-York-NY-10023/2100774851_zpid/,http://www.zillow.com/homedetails/219-W-78th-St-APT-2F-New-York-NY-10024/2100775303_zpid/,http://www.zillow.com/homedetails/405-W-49th-St-APT-2W-New-York-NY-10019/2100776286_zpid/,http://www.zillow.com/homedetails/230-E-26th-St-APT-3A-New-York-NY-10010/2100776283_zpid/,http://www.zillow.com/homedetails/319-E-53rd-St-APT-2B-New-York-NY-10022/2104750345_zpid/,http://www.zillow.com/homedetails/53-Irving-Pl-APT-3K-New-York-NY-10003/2103128441_zpid/,http://www.zillow.com/homedetails/25-E-67th-St-APT-8D-New-York-NY-10065/2100777265_zpid/,http://www.zillow.com/homedetails/303-E-73rd-St-E-New-York-NY-10021/2100777278_zpid/,http://www.zillow.com/homedetails/422-E-81st-St-APT-4A-New-York-NY-10028/2111603077_zpid/,http://www.zillow.com/homedetails/445-W-49th-St-APT-3B-New-York-NY-10019/2106388119_zpid/,http://www.zillow.com/homedetails/203-E-121st-St-APT-901-New-York-NY-10035/2100777283_zpid/,http://www.zillow.com/homedetails/434-E-72nd-St-APT-2C-New-York-NY-10021/2120058527_zpid/
routable_link/_text,"9 E 129th St # 1, New York, NY10035","710 Riverside Dr APT 2C, New York, NY10031","413 E 84th St APT 8, New York, NY10028","324 Pleasant Ave APT 6E, New York, NY10035","217 Thompson St APT 6, New York, NY10012","340 W 47th St APT 4C, New York, NY10036","1356 1st Ave APT 5B, New York, NY10021","101 W 77th St APT 3C, New York, NY10024","111 W 74th St APT 2R, New York, NY10023","646 10th Ave APT 4B, New York, NY10036","76 Carmine St APT 4C, New York, NY10014","146 W 120th St APT 8, New York, NY10027","137 W 72nd St APT 4FE, New York, NY10023","178 Avenue B # 2, New York, NY10009","95 Wall St, New York, NY",...,"304 E 41st St APT 1107A, New York, NY10017","169 Avenue A APT 1, New York, NY10009","722 10th Ave APT 3A, New York, NY10019","200 W 70th St APT 11L3, New York, NY10023","219 W 78th St APT 2F, New York, NY10024","405 W 49th St APT 2W, New York, NY10019","230 E 26th St APT 3A, New York, NY10010","319 E 53rd St APT 2B, New York, NY10022","53 Irving Pl APT 3K, New York, NY10003","25 E 67th St APT 8D, New York, NY10065","303 E 73rd St # E, New York, NY10021","422 E 81st St APT 4A, New York, NY10028","445 W 49th St APT 3B, New York, NY10019","203 E 121st St APT 901, New York, NY10035","434 E 72nd St APT 2C, New York, NY10021"
routable_link/_title,"9 E 129th St # 1, New York, NY Real Estate","710 Riverside Dr APT 2C, New York, NY Real Estate","413 E 84th St APT 8, New York, NY Real Estate","324 Pleasant Ave APT 6E, New York, NY Real Estate","217 Thompson St APT 6, New York, NY Real Estate","340 W 47th St APT 4C, New York, NY Real Estate","1356 1st Ave APT 5B, New York, NY Real Estate","101 W 77th St APT 3C, New York, NY Real Estate","111 W 74th St APT 2R, New York, NY Real Estate","646 10th Ave APT 4B, New York, NY Real Estate","76 Carmine St APT 4C, New York, NY Real Estate","146 W 120th St APT 8, New York, NY Real Estate","137 W 72nd St APT 4FE, New York, NY Real Estate","178 Avenue B # 2, New York, NY Real Estate","95 Wall, Studio E1O Real Estate",...,"304 E 41st St APT 1107A, New York, NY Real Estate","169 Avenue A APT 1, New York, NY Real Estate","722 10th Ave APT 3A, New York, NY Real Estate","200 W 70th St APT 11L3, New York, NY Real Estate","219 W 78th St APT 2F, New York, NY Real Estate","405 W 49th St APT 2W, New York, NY Real Estate","230 E 26th St APT 3A, New York, NY Real Estate","319 E 53rd St APT 2B, New York, NY Real Estate","53 Irving Pl APT 3K, New York, NY Real Estate","25 E 67th St APT 8D, New York, NY Real Estate","303 E 73rd St # E, New York, NY Real Estate","422 E 81st St APT 4A, New York, NY Real Estate","445 W 49th St APT 3B, New York, NY Real Estate","203 E 121st St APT 901, New York, NY Real Estate","434 E 72nd St APT 2C, New York, NY Real Estate"
routable_link_numbers,9; 129; 1,710; 2,413; 84; 8,324; 6,217; 6,340; 47; 4,1356; 1; 5,101; 77; 3,111; 74; 2,646; 10; 4,76; 4,146; 120; 8,137; 72; 4,178; 2,95,...,304; 41; 1107,169; 1,722; 10; 3,200; 70; 11,219; 78; 2,405; 49; 2,230; 26; 3,319; 53; 2,53; 3,25; 67; 8,303; 73,422; 81; 4,445; 49; 3,203; 121; 901,434; 72; 2
listingtype_value,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,...,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent
pricelarge_value,"$1,750/mo","$3,000/mo","$2,300/mo","$2,500/mo","$2,800/mo","$2,490/mo","$2,750/mo","$2,150/mo","$2,875/mo","$2,225/mo","$2,450/mo","$1,800/mo","$2,850/mo","$2,700/mo","$3,000+/mo",...,"$2,200/mo","$2,195/mo","$2,995/mo","$1,895/mo","$2,493/mo","$2,925/mo","$2,940/mo","$2,170/mo","$2,300/mo","$2,600/mo","$2,265/mo","$2,150/mo","$2,195/mo","$1,795/mo","$2,150/mo"
pricelarge_value_prices,1.75e+03,3e+03,2.3e+03,2.5e+03,2.8e+03,2.49e+03,2.75e+03,2.15e+03,2.88e+03,2.22e+03,2.45e+03,1.8e+03,2.85e+03,2.7e+03,3e+03,...,2.2e+03,2.2e+03,3e+03,1.9e+03,2.49e+03,2.92e+03,2.94e+03,2.17e+03,2.3e+03,2.6e+03,2.26e+03,2.15e+03,2.2e+03,1.8e+03,2.15e+03
propertyinfo_value,1 bd • 1 ba,"2 bds • 2 ba • 1,016 sqft",Studio • 1 ba,2 bds • 1 ba,2 bds • 1 ba,1 bd • 1 ba,"1 bd • 1 ba • 496 sqft • 4,502 sqft lot • Built 1900",Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba,Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba • 700 sqft,1 bd • 1 ba,Studio • 1 ba • 487 sqft,...,Studio • 1 ba,Studio • 1 ba,1 bd • 1 ba • 475 sqft • Built 1900,Studio • 1 ba,1 bd • 1 ba • 500 sqft,2 bds • 1 ba,2 bds • 1 ba,Studio • 1 ba,Studio • 1 ba • 400 sqft,Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba,Studio • 1 ba,Studio • 1 ba • 550 sqft,1 bd • 1 ba
propertyinfo_value_numbers,1; 1,2; 2; 1016,1,2; 1,2; 1,1; 1,1; 1; 496; 4502; 1900,1,1; 1,1; 1,1,1; 1,1; 1; 700,1; 1,1; 487,...,1,1,1; 1; 475; 1900,1,1; 1; 500,2; 1,2; 1,1,1; 400,1,1; 1,1; 1,1,1; 550,1; 1
fineprint_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fineprint_value_numbers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tozcount_number,48,1,2,2,3,6,6,6,6,6,7,9,9,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tozfresh_value,minutes ago,hour ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,Updated today,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tablegrouped_values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tablegrouped_values_prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
_PAGE_NUMBER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...,19,19,20,20,20,20,20,20,20,20,20,20,20,20,20

In [18]:
len(su[su['pricelarge_value_prices'].isnull()]) # 确认所有记录都有价格字段

0

In [19]:
su['propertyinfo_value'].head(20)

2                                              1 bd • 1 ba
3                                2 bds • 2 ba • 1,016 sqft
4                                            Studio • 1 ba
5                                             2 bds • 1 ba
7                                             2 bds • 1 ba
10                                             1 bd • 1 ba
11    1 bd • 1 ba • 496 sqft • 4,502 sqft lot • Built 1900
12                                           Studio • 1 ba
13                                             1 bd • 1 ba
17                                             1 bd • 1 ba
18                                           Studio • 1 ba
19                                             1 bd • 1 ba
20                                  1 bd • 1 ba • 700 sqft
21                                             1 bd • 1 ba
23                                Studio • 1 ba • 487 sqft
24                                            2 bds • 1 ba
27                                  1 bd • 1 ba • 525 sqft
29                                 2 bds • 1 ba • 650 sqft
30                                             1 bd • 1 ba
33                                             1 bd • 1 ba
Name: propertyinfo_value, dtype: object

In [20]:
# check the number of rows that do not contain 'bd' or 'Studio'
len(su[~(su['propertyinfo_value'].str.contains('Studio')|su['propertyinfo_value'].str.contains('bd'))])

0

In [21]:
# check the number of row that do not contain 'ba'
len(su[~(su['propertyinfo_value'].str.contains('ba'))])

6

In [22]:
# select those listings with a bath
no_baths = su[~(su['propertyinfo_value'].str.contains('ba'))] # 这是没有浴室的房源

In [23]:
# exclude those missing bathroom info
sucln = su[~su.index.isin(no_baths.index)] # 将没有浴室的房源排除掉

In [24]:
sucln

,routablemask_link,routablemask_link/_text,routablemask_link/_title,routablemask_link_numbers,routablemask_content,imagebadge_value,imagebadge_value_numbers,routable_link,routable_link/_text,routable_link/_title,routable_link_numbers,listingtype_value,pricelarge_value,pricelarge_value_prices,propertyinfo_value,propertyinfo_value_numbers,fineprint_value,fineprint_value_numbers,tozcount_number,tozfresh_value,tablegrouped_values,tablegrouped_values_prices,_PAGE_NUMBER
2,http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,"9 E 129th St # 1, New York, NY10035","9 E 129th St # 1, New York, NY Real Estate",9; 129; 1,Apartment For Rent,"$1,750/mo",1750.0,1 bd • 1 ba,1; 1,NaN,NaN,48.0,minutes ago,NaN,NaN,1
3,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,9 photos,NaN,9.0,NaN,9 photos,9.0,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,"710 Riverside Dr APT 2C, New York, NY10031","710 Riverside Dr APT 2C, New York, NY Real Estate",710; 2,Apartment For Rent,"$3,000/mo",3000.0,"2 bds • 2 ba • 1,016 sqft",2; 2; 1016,NaN,NaN,1.0,hour ago,NaN,NaN,1
4,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,5 photos,NaN,5.0,NaN,5 photos,5.0,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,"413 E 84th St APT 8, New York, NY10028","413 E 84th St APT 8, New York, NY Real Estate",413; 84; 8,Apartment For Rent,"$2,300/mo",2300.0,Studio • 1 ba,1,NaN,NaN,2.0,hours ago,NaN,NaN,1
5,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,7 photos,NaN,7.0,NaN,7 photos,7.0,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,"324 Pleasant Ave APT 6E, New York, NY10035","324 Pleasant Ave APT 6E, New York, NY Real Estate",324; 6,Apartment For Rent,"$2,500/mo",2500.0,2 bds • 1 ba,2; 1,NaN,NaN,2.0,hours ago,NaN,NaN,1
7,http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,"217 Thompson St APT 6, New York, NY10012","217 Thompson St APT 6, New York, NY Real Estate",217; 6,Apartment For Rent,"$2,800/mo",2800.0,2 bds • 1 ba,2; 1,NaN,NaN,3.0,hours ago,NaN,NaN,1
10,http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,"340 W 47th St APT 4C, New York, NY10036","340 W 47th St APT 4C, New York, NY Real Estate",340; 47; 4,Apartment For Rent,"$2,490/mo",2490.0,1 bd • 1 ba,1; 1,NaN,NaN,6.0,hours ago,NaN,NaN,1
11,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,9 photos,NaN,9.0,NaN,9 photos,9.0,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,"1356 1st Ave APT 5B, New York, NY10021","1356 1st Ave APT 5B, New York, NY Real Estate",1356; 1; 5,Apartment For Rent,"$2,750/mo",2750.0,"1 bd • 1 ba • 496 sqft • 4,502 sqft lot • Built 1900",1; 1; 496; 4502; 1900,NaN,NaN,6.0,hours ago,NaN,NaN,1
12,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,"101 W 77th St APT 3C, New York, NY10024","101 W 77th St APT 3C, New York, NY Real Estate",101; 77; 3,Apartment For Rent,"$2,150/mo",2150.0,Studio • 1 ba,1,NaN,NaN,6.0,hours ago,NaN,NaN,1
13,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,6 photos,NaN,6.0,NaN,6 photos,6.0,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,"111 W 74th St APT 2R, New York, NY10023","111 W 74th St APT 2R, New York, NY Real Estate",111; 74; 2,Apartment For Rent,"$2,875/mo",2875.0,1 bd • 1 ba,1; 1,NaN,NaN,6.0,hours ago,NaN,NaN,1
17,http://www.zillow.com/homedetails/646-10th-Ave-APT-4B-New-York-NY-10036/2114397534_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/646-10th-Ave-APT-4B-New-York-NY-10036/2114397534_zpid/,"646 10th Ave APT 4B, New York, NY10036","646 10th Ave APT 4B, New York, NY Real Estate",646; 10; 4,Apartment For Rent,"$2,225/mo",2225.0,1 bd • 1 ba,1; 1,NaN,NaN,6.0,hours ago,NaN,NaN,1
18,http://www.zillow.com/homedetails/76-Carmine-St-APT-4C-New-York-NY-10014/2110813540_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/76-Carmine-St-APT-4C-New-York-NY-10014/2110813540_zpid/,"76 Carmine St APT 4C, New York, NY10014","76 Carmine St APT 4C, New York, NY Real Estate",76; 4,Apartment For Rent,"$2,450/mo",2450.0,Studio • 1 ba,1,NaN,NaN,7.0,hours ago,NaN,NaN,1
19,http://www.zillow.com/homedetails/146-W-120th-St-APT-8-New-York-NY-10027/2100762986_zpid/,6 photos,NaN,6.0,NaN,6 photos,6.0,http://www.zillow.com/homedetails/146-W-120th-St-APT-8-New-York-NY-10027/2100762986_zpid/,"146 W 120th St APT 8, New York, NY10027","146 W 120th St APT 8, New York, NY Real Estate",146; 120; 8,Apartment For Rent,"$1,800/mo",1800.0,1 bd • 1 ba,1; 1,NaN,NaN,9.0,hours ago,NaN,NaN,1
20,http://www.zillow.com/homedetails/137-W-72nd-St-APT-4FE-New-York-NY-10023/2105480982_zpid/,10 photos,NaN,10.0,NaN,10 photos,10.0,http://www.zillow.com/homedetails/137-W-72nd-St-APT-4FE-New-York-NY-10023/2105480982_zpid/,"137 W 72nd St APT 4FE, New York, NY10023","137 W 72nd St APT 4FE, New York, NY Real Estate",137; 72; 4,Apartment For Rent,"$2,850/mo",2850.0,1 bd • 1 ba • 700 sqft,1; 1; 700,NaN,NaN,9.0,hours ago,NaN,NaN,1
21,http://www.zillow.com/homedetails/178-Avenue-B-2-New-York-NY-10009/2100763265_zpid/,6 photos,NaN,6.0,NaN,6 photos,6.0,http://www.zillow.com/homedetails/178-Avenue-B-2-New-York-NY-10009/2100763265_zpid/,"178 Avenue B # 2, New York, NY10009","178 Avenue B # 2, New York, NY Real Estate",178; 2,Apartment For Rent,"$2,700/mo",2700.0,1 bd • 1 ba,1; 1,NaN,NaN,10.0,hours ago,NaN,NaN,1
23,http://www.zillow.com/homedetails/95-Wall-St-72791-New-York-NY-10005/2103168440_zpid/,17 photos,NaN,17.0,NaN,17 photos,17.0,http://www.zillow.com/homedetails/95-Wall-St-72791-New-York-NY-10005/2103168440_zpid/,"95 Wall St, New York, NY","95 Wall, Studio E1O Real Estate",95,Apartment For Rent,"$3,000+/mo",3000.0,Studio • 1 ba • 487 sqft,1; 487,NaN,NaN,NaN,Updated today,NaN,NaN,1
24,http://www.zillow.com/homedetails/129-Rivington-St-FRNT-2F-New-York-NY-10002/2100765545_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/129-Rivington-St-FRNT-2F-New-York-NY-10002/2100765545_zpid/,"129 Rivington St FRNT 2F, New York, NY10002","129 Rivington St FRNT 2F, New York, NY Real Estate",129; 2,Apartment For Rent,"$2,995/mo",2995.0,2 bds • 1 ba,2; 1,NaN,NaN,18.0,hours ago,NaN,NaN,1
27,http://www.zillow.com/homedetails/211-E-4th-St-APT-3-New-York-NY-10009/2119571597_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/211-E-4th-St-APT-3-New-York-NY-10009/2119571597_zpid/,"211 E 4th St APT 3, New York, NY10009","211 E 4th St APT 3, New York, NY Real Estate",211; 4; 3,Apartment For Rent,"$2,700/mo",2700.0,1 bd • 1 ba • 525 sqft,1; 1; 525,NaN,NaN,NaN,NaN,NaN,NaN,2
29,http://www.zillow.com/homedetails/52-Allen-St-3-New-York-NY-10002/2100767061_zpid/,11 photos,NaN,11.0,NaN,11 photos,11.0,http://www.zillow.com/homedetails/52-Allen-St-3-New-York-NY-10002/2100767061_zpid/,"52 Allen St # 3, New York, NY10002","52 Allen St # 3, New York, NY Real Estate",52; 3,Apartment For Rent,"$2,800/mo",2800.0,2 bds • 1 ba • 650 sqft,2; 1; 650,NaN,NaN,NaN,NaN,NaN,NaN,2
30,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/280-E-2nd-St-604-New-York-NY-10009/2100767100_zpid/,"280 E 2nd St # 604, New York, NY10009","280 E 2nd St # 604, New York, NY Real Estate",280; 2; 604,Apartment For Rent,"$2,850/mo",2850.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,2
33,http://www.zillow.com/homedetails/201-Allen-St-2R-New-York-NY-10002/2100769330_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/201-Allen-St-2R-New-York-NY-10002/2100769330_zpid/,"201 Allen St # 2R, New York, NY10002","201 Allen St # 2R, New York, NY Real Estate",201; 2,Apartment For Rent,"$2,199/mo",2199.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,2
36,http://www.zillow.com/homedetails/74-Leonard-St-APT-2B-New-York-NY-10013/2100769387_zpid/,7 photos,NaN,7.0,NaN,7 photos,7.0,http://www.zillow.com/homedetails/74-Leonard-St-APT-2B-New-York-NY-10013/2100769387_zpid/,"74 Leonard St APT 2B, New York, NY10013","74 Leonard St APT 2B, New York, NY Real Estate",74; 2,Apartment For Rent,"$2,895/mo",2895.0,Studio • 1 ba,1,NaN,NaN,NaN,NaN,NaN,NaN,2
38,http://www.zillow.com/homedetails/70-Orchard-St-APT-6-New-York-NY-10002/2100774367_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/70-Orchard-St-APT-6-New-York-NY-10002/2100774367_zpid/,"70 Orchard St APT 6, New York, NY10002","70 Orchard St APT 6, New York, NY Real Estate",70; 6,Apartment For Rent,"$2,200/mo",2200.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,2
40,http://www.zillow.com/homedetails/1-West-St-APT-2040-New-York-NY-10004/2127108261_zpid/,11 photos,NaN,11.0,NaN,11 photos,11.0,http://www.zillow.com/homedetails/1-West-St-APT-2040-New-York-NY-10004/2127108261_zpid/,"1 West St APT 2040, New York, NY10004","1 West St APT 2040, New York, NY Real Estate",1; 2040,Apartment For Rent,"$2,600/mo",2600.0,Studio • 1 ba • 406 sqft • Built 1903,1; 406; 1903,NaN,NaN,NaN,NaN,NaN,NaN,2
42,http://www.zillow.com/homedetails/166-W-76th-St-APT-4E-New-York-NY-10023/2118825231_zpid/,5 photos,NaN,5.0,NaN,5 photos,5.0,http://www.zillow.com/homedetails/166-W-76th-St-APT-4E-New-York-NY-10023/2118825231_zpid/,"166 W 76th St APT 4E, New York, NY10023","166 W 76th St APT 4E, New York, NY Real Estate",166; 76; 4,Apartment For Rent,"$2,300/mo",2300.0,Studio • 1 ba • 350 sqft • 465 sqft lot,1; 350; 465,NaN,NaN,12.0,hours ago,NaN,NaN,2
44,http://www.zillow.com/homedetails/72-W-87th-St-1D-New-York-NY-10024/2100763839_zpid/,1 photo,NaN,1.0,NaN,1 photo,1.0,http://www.zillow.com/homedetails/72-W-87th-St-1D-New-York-NY-10024/2100763839_zpid/,"72 W 87th St # 1D, New York, NY10024","72 W 87th St # 1D, New York, NY Real Estate",72; 87; 1,Apartment For Rent,"$2,400/mo",2400.0,Studio • 1 ba,1,NaN,NaN,12.0,hours ago,NaN,NaN,2
45,http://www.zillow.com/homedetails/310-W-78th-St-3BB-New-York-NY-10024/2100763841_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/310-W-78th-St-3BB-New-York-NY-10024/2100763841_zpid/,"310 W 78th St # 3BB, New York, NY10024","310 W 78th St # 3BB, New York, NY Real Estate",310; 78; 3,Apartment For Rent,"$2,195/mo",2195.0,Studio • 1 ba • 400 sqft,1; 400,NaN,NaN,12.0,hours ago,NaN,NaN,2
46,http://www.zillow.com/homedetails/301-W-110th-St-APT-3F-New-York-NY-10026/31550221_zpid/,11 photos,NaN,11.0,NaN,11 photos,11.0,http://www.zillow.com/homedetails/301-W-110th-St-APT-3F-New-York-NY-10026/31550221_zpid/,"301 W 110th St APT 3F, New York, NY10026","301 W 110th St APT 3F, New York, NY Real Estate",301; 110; 3,Apartment For Rent,"$2,800/mo",2800.0,1 bd • 1 ba • 600 sqft • Built 1989,1; 1; 600; 1989,NaN,NaN,12.0,hours ago,NaN,NaN,2
47,http://www.zillow.com/homedetails/115-W-57th-St-APT-4F-New-York-NY-10019/2118533935_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/115-W-57th-St-APT-4F-New-York-NY-10019/2118533935_zpid/,"115 W 57th St APT 4F, New York, NY10019","115 W 57th St APT 4F, New York, NY Real Estate",115; 57; 4,Apartment For Rent,"$2,495/mo",2495.0,1 bd • 1 ba,1; 1,NaN,NaN,14.0,hours ago,NaN,NaN,2
48,http://www.zillow.com/homedetails/438-E-66th-St-4-New-York-NY-10065/2106344724_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/438-E-66th-St-4-New-York-NY-10065/2106344724_zpid/,"438 E 66th St # 4, New York, NY10065","438 E 66th St # 4, New York, NY Real Estate",438; 66; 4,Apartment For Rent,"$1,900/mo",1900.0,1 bd • 1 ba,1; 1,NaN,NaN,14.0,hours ago,NaN,NaN,2
49,http://www.zillow.com/homedetails/30-W-141st-St-APT-6C-New-York-NY-10037/2112163749_zpid/,9 photos,NaN,9.0,NaN,9 photos,9.0,http://www.zillow.com/homedetails/30-W-141st-St-APT-6C-New-York-NY-10037/2112163749_zpid/,"30 W 141st St APT 6C, New York, NY10037","30 W 141st St APT 6C, New York, NY Real Estate",30; 141; 6,Apartment For Rent,"$1,815/mo",1815.0,1 bd • 1 ba • 596 sqft • Built 1959,1; 1; 596; 1959,NaN,NaN,14.0,hours ago,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,http://www.zillow.com/homedetails/3924-Broadway-APT-2A-New-York-NY-10032/2101999887_zpid/,8 photos,NaN,8.0,NaN,8 photos,8.0,http://www.zillow.com/homedetails/3924-Broadway-APT-2A-New-York-NY-10032/2101999887_zpid/,"3924 Broadway APT 2A, New York, NY10032","3924 Broadway APT 2A, New York, NY Real Estate",3924; 2,Apartment For Rent,"$2,095/mo",2095.0,2 bds • 1 ba • 900 sqft,2; 1; 900,NaN,NaN,NaN,NaN,NaN,NaN,19
451,http://www.zillow.com/homedetails/534-W-159th-St-APT-2D-New-York-NY-10032/2106895748_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/534-W-159th-St-APT-2D-New-York-NY-10032/2106895748_zpid/,"534 W 159th St APT 2D, New York, NY10032","534 W 159th St APT 2D, New York, NY Real Estate",534; 159; 2,Apartment For Rent,"$2,000/mo",2000.0,2 bds • 1 ba,2; 1,NaN,NaN,NaN,NaN,NaN,NaN,19
452,http://www.zillow.com/homedetails/21-E-108th-St-APT-1B-New-York-NY-10029/2124237773_zpid/,6 photos,NaN,6.0,NaN,6 photos,6.0,http://www.zillow.com/homedetails/21-E-108th-St-APT-1B-New-York-NY-10029/2124237773_zpid/,"21 E 108th St APT 1B, New York, NY10029","21 E 108th St APT 1B, New York, NY Real Estate",21; 108; 1,Apartment For Rent,"$2,095/mo",2095.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,19
453,http://www.zillow.com/homedetails/346-E-49th-St-5-New-York-NY-10017/2100771935_zpid/,1 photo,NaN,1.0,NaN,1 photo,1.0,http://www.zillow.com/homedetails/346-E-49th-St-5-New-York-NY-10017/2100771935_zpid/,"346 E 49th St # 5, New York, NY10017","346 E 49th St # 5, New York, NY Real Estate",346; 49; 5,Apartment For Rent,"$2,250/mo",2250.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,19
454,http://www.zillow.com/homedetails/528-E-79th-St-APT-3D-New-York-NY-10075/2124593208_zpid/,11 photos,NaN,11.0,NaN,11 photos,11.0,http://www.zillow.com/homedetails/528-E-79th-St-APT-3D-New-York-NY-10075/2124593208_zpid/,"528 E 79th St APT 3D, New York, NY10075","528 E 79th St APT 3D, New York, NY Real Estate",528; 79; 3,Apartment For Rent,"$2,450/mo",2450.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,19
457,http://www.zillow.com/homedetails/372-Central-Park-W-APT-9S-New-York-NY-10025/31548363_zpid/,5 photos,NaN,5.0,NaN,5 photos,5.0,http://www.zillow.com/homedetails/372-Central-Park-W-APT-9S-New-York-NY-10025/31548363_zpid/,"372 Central Park W APT 9S, New York, NY10025","372 Central Park W APT 9S, New York, NY Real Estate",372; 9,Apartment For Rent,"$2,500/mo",2500.0,Studio • 1 ba • 540 sqft • 2.00 ac lot • Built 1961,1; 540; 2; 1961,NaN,NaN,NaN,NaN,NaN,NaN,19
458,http://www.zillow.com/homedetails/305-E-75th-St-APT-19-New-York-NY-10021/2100771931_zpid/,5 photos,NaN,5.0,NaN,5 photos,5.0,http://www.zillow.com/homedetails/305-E-75th-St-APT-19-New-York-NY-10021/2100771931_zpid/,"305 E 75th St APT 19, New York, NY10021","305 E 75th St APT 19, New York, NY Real Estate",305; 75; 19,Apartment For Rent,"$2,500/mo",2500.0,2 bds • 1 ba,2; 1,NaN,NaN,NaN,NaN,NaN,NaN,19
459,http://www.zillow.com/homedetails/423-E-77th-St-APT-5B-New-York-NY-10075/2100771933_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/423-E-77th-St-APT-5B-New-York-NY-10075/2100771933_zpid/,"423 E 77th St APT 5B, New York, NY10075","423 E 77th St APT 5B, New York, NY Real Estate",423; 77; 5,Apartment For Rent,"$1,800/mo",1800.0,Studio • 1 ba,1,NaN,NaN,NaN,NaN,NaN,NaN,19
460,http://www.zillow.com/homedetails/215-E-10th-St-APT-16-New-York-NY-10003/2117980609_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/215-E-10th-St-APT-16-New-York-NY-10003/2117980609_zpid/,"215 E 10th St APT 16, New York, NY10003","215 E 10th St APT 16, New York, NY Real Estate",215; 10; 16,Apartment For Rent,"$2,495/mo",2495.0,1 bd • 1 ba,1; 1,NaN,NaN,NaN,NaN,NaN,NaN,19
461,http://www.zillow.com/homedetails/175-E-96th-St-335756-New-York-NY-10128/2100798508_zpid/,10 photos,NaN,10.0,NaN,10 photos,10.0,http://www.zillow.com/homedetails/175-E-96th-St-335756-New-York-NY-10128/2100798508_zpid/,"175 E 96th St, New York, NY","The Monterey, Studio 1 ba Real Estate",175; 96,Apartment For Rent,"$2,950+/mo",2950.0,Studio • 1 ba,1,NaN,NaN,NaN,NaN,NaN,NaN,19
462,http://www.zillow.com/homedetails/235-W-48th-St-266094-New-York-NY-10036/2100905890_zpid/,13 photos,NaN,13.0,NaN,13 photos,13.0,http://www.zillow.com/homedetails/235-W-48th-St-266094-New-York-NY-10036/2100905890_zpid/,"235 W 48th St, New York, NY","The Ritz Plaza, Studio 1 ba Real Estate",235; 48,Apartment For Rent,"$2,950+/mo",2950.0,Studio • 1 ba • Built 1993,1; 1993,NaN,NaN,NaN,NaN,NaN,NaN,19
464,http://www.zillow.com/homedetails/330-E-33rd-St-APT-20G-New-York-NY-10016/31510167_zpid/,NaN,NaN,NaN,NaN,NaN,NaN,http://www.zillow.com/homedetails/330-E-33rd-St-APT-20G-New-York-NY-10016/31510167_zpid/,"330 E 33rd St APT 20G, New York, NY10016","330 E 33rd St APT 20G, New York, NY Real Estate",330; 33; 20,Apartment For Rent,"$2,500/mo",2500.0,Studio • 1 ba • 485 sqft • Built 1962,1; 485; 1962,NaN,NaN,NaN,NaN,NaN,NaN,19
466,http://www.zillow.com/homedetails/238-W-20th-St-2FW-New-York-NY-10011/2100772861_zpid/,4 photos,NaN,4.0,NaN,4 photos,4.0,http://www.zillow.com/homedetails/238-W-20th-St-2FW-New-York-NY-10011/2100772861_zpid/,"238 W 20th St # 2FW, New York, NY10011","238 W 20th St # 2FW, New York, NY Real Estate",238; 20; 2,Apartment For Rent,"$2,595/mo",2595.0,2 bds • 1 ba • 600 sqft,2; 1; 600,NaN,NaN,NaN,NaN,NaN,NaN,19
467,http://www.zillow.com/homedetails/525-W-28th-St-607844-New-York-NY-10001/2103477944_zpid/,32 photos,NaN,32.0,NaN,32 photos,32.0,http://www.zillow.com/homedetails/525-W-28th-St-607844-New-York-NY-10001/2103477944_zpid/,"525 W 28th St, New York, NY","AVA High Line, S21 Real Estate",525; 28,Apartment For Rent,"$2,965+/mo",2965.0,Studio • 1 ba • 522 sqft • Built 2013,1; 522; 2013,NaN,NaN,NaN,NaN,NaN,NaN,19
468,http://www.zillow.com/homedetails/377-E-33rd-St-607370-New-York-NY-10016/2103465169_zpid/,12 photos,NaN,12.0,NaN,12 photos,12.0,http://www.zillow.com/homedetails/377-E-33rd-St-607370-New-York-NY-10016/2103465169_zpid/,"377 E 33rd St, New York, NY","Avalon Kips Bay, 480 Real Estate",377; 33,Apartment For Rent,"$2,815+/mo",2815.0,Studio • 1 ba • 480 sqft • Built 1998,1; 480; 1998,NaN,NaN,NaN,NaN,NaN,NaN,19
470,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/,5 photos,NaN,5.0,NaN,5 photos,5.0,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/,"304 E 41st St APT 1107A, New York, NY10017","304 E 41st St APT 1107A, New York, NY Real Estate",304; 41; 1107,Apartment For Rent,"$2,200/mo",2200.0,Studio • 1 ba,1,NaN,NaN,NaN,NaN,NaN,NaN,19
471,http://www.zillow.com/homedetails/169-Avenue-A-APT-1-New-York-NY-10009/2105208117_zpid/,8 photos,NaN,8.0,NaN,8 photos,8.0,http://www.zillow.com/homedetails/169-Avenue-A-APT-1-New-York-NY-10009/2105208117_zpid/,"169 Avenue A APT 1, New York, NY10009","169 Avenue A APT 1, New York, NY Real Estate",169; 1,Apartment For Rent,"$2,195/mo",2195.0,Studio • 1 ba,1,NaN,NaN,NaN,NaN,NaN,NaN,19

In [25]:
# split using the bullet
def parse_info(row):
        if not 'sqft' in row:
            br, ba = row.split('•')[:2]
            sqft = np.nan
        else:
            br, ba, sqft = row.split('•')[:3]                
        return pd.Series({'Beds': br, 'Baths': ba, 'Sqft': sqft})

In [26]:
attr = sucln['propertyinfo_value'].apply(parse_info) # 按照•分割成多个字段

In [27]:
attr.head()

    Baths     Beds         Sqft
2    1 ba    1 bd           NaN
3   2 ba    2 bds    1,016 sqft
4    1 ba  Studio           NaN
5    1 ba   2 bds           NaN
7    1 ba   2 bds           NaN

In [28]:
#remove the strings from our values 删除掉ba、bd sqft等字串
attr_cln = attr.applymap(lambda x: x.strip().split(' ')[0] if isinstance(x,str) else np.nan)

attr_cln.head()

  Baths    Beds   Sqft
2     1       1    NaN
3     2       2  1,016
4     1  Studio    NaN
5     1       2    NaN
7     1       2    NaN

In [29]:
sujnd = sucln.join(attr_cln)

In [30]:
sujnd.T # 完成了卧室、浴室和平方英尺字段的拆分

,2,3,4,5,7,10,11,12,13,17,18,19,20,21,23,...,470,471,475,477,479,483,484,485,486,487,490,492,496,497,499
routablemask_link,http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,http://www.zillow.com/homedetails/646-10th-Ave-APT-4B-New-York-NY-10036/2114397534_zpid/,http://www.zillow.com/homedetails/76-Carmine-St-APT-4C-New-York-NY-10014/2110813540_zpid/,http://www.zillow.com/homedetails/146-W-120th-St-APT-8-New-York-NY-10027/2100762986_zpid/,http://www.zillow.com/homedetails/137-W-72nd-St-APT-4FE-New-York-NY-10023/2105480982_zpid/,http://www.zillow.com/homedetails/178-Avenue-B-2-New-York-NY-10009/2100763265_zpid/,http://www.zillow.com/homedetails/95-Wall-St-72791-New-York-NY-10005/2103168440_zpid/,...,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/,http://www.zillow.com/homedetails/169-Avenue-A-APT-1-New-York-NY-10009/2105208117_zpid/,http://www.zillow.com/homedetails/722-10th-Ave-APT-3A-New-York-NY-10019/2126268388_zpid/,http://www.zillow.com/homedetails/200-W-70th-St-APT-11L3-New-York-NY-10023/2100774851_zpid/,http://www.zillow.com/homedetails/219-W-78th-St-APT-2F-New-York-NY-10024/2100775303_zpid/,http://www.zillow.com/homedetails/405-W-49th-St-APT-2W-New-York-NY-10019/2100776286_zpid/,http://www.zillow.com/homedetails/230-E-26th-St-APT-3A-New-York-NY-10010/2100776283_zpid/,http://www.zillow.com/homedetails/319-E-53rd-St-APT-2B-New-York-NY-10022/2104750345_zpid/,http://www.zillow.com/homedetails/53-Irving-Pl-APT-3K-New-York-NY-10003/2103128441_zpid/,http://www.zillow.com/homedetails/25-E-67th-St-APT-8D-New-York-NY-10065/2100777265_zpid/,http://www.zillow.com/homedetails/303-E-73rd-St-E-New-York-NY-10021/2100777278_zpid/,http://www.zillow.com/homedetails/422-E-81st-St-APT-4A-New-York-NY-10028/2111603077_zpid/,http://www.zillow.com/homedetails/445-W-49th-St-APT-3B-New-York-NY-10019/2106388119_zpid/,http://www.zillow.com/homedetails/203-E-121st-St-APT-901-New-York-NY-10035/2100777283_zpid/,http://www.zillow.com/homedetails/434-E-72nd-St-APT-2C-New-York-NY-10021/2120058527_zpid/
routablemask_link/_text,NaN,9 photos,5 photos,7 photos,NaN,NaN,9 photos,4 photos,6 photos,NaN,4 photos,6 photos,10 photos,6 photos,17 photos,...,5 photos,8 photos,5 photos,4 photos,6 photos,5 photos,6 photos,5 photos,6 photos,NaN,5 photos,4 photos,4 photos,4 photos,1 photo
routablemask_link/_title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
routablemask_link_numbers,NaN,9,5,7,NaN,NaN,9,4,6,NaN,4,6,10,6,17,...,5,8,5,4,6,5,6,5,6,NaN,5,4,4,4,1
routablemask_content,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
imagebadge_value,NaN,9 photos,5 photos,7 photos,NaN,NaN,9 photos,4 photos,6 photos,NaN,4 photos,6 photos,10 photos,6 photos,17 photos,...,5 photos,8 photos,5 photos,4 photos,6 photos,5 photos,6 photos,5 photos,6 photos,NaN,5 photos,4 photos,4 photos,4 photos,1 photo
imagebadge_value_numbers,NaN,9,5,7,NaN,NaN,9,4,6,NaN,4,6,10,6,17,...,5,8,5,4,6,5,6,5,6,NaN,5,4,4,4,1
routable_link,http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,http://www.zillow.com/homedetails/646-10th-Ave-APT-4B-New-York-NY-10036/2114397534_zpid/,http://www.zillow.com/homedetails/76-Carmine-St-APT-4C-New-York-NY-10014/2110813540_zpid/,http://www.zillow.com/homedetails/146-W-120th-St-APT-8-New-York-NY-10027/2100762986_zpid/,http://www.zillow.com/homedetails/137-W-72nd-St-APT-4FE-New-York-NY-10023/2105480982_zpid/,http://www.zillow.com/homedetails/178-Avenue-B-2-New-York-NY-10009/2100763265_zpid/,http://www.zillow.com/homedetails/95-Wall-St-72791-New-York-NY-10005/2103168440_zpid/,...,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/,http://www.zillow.com/homedetails/169-Avenue-A-APT-1-New-York-NY-10009/2105208117_zpid/,http://www.zillow.com/homedetails/722-10th-Ave-APT-3A-New-York-NY-10019/2126268388_zpid/,http://www.zillow.com/homedetails/200-W-70th-St-APT-11L3-New-York-NY-10023/2100774851_zpid/,http://www.zillow.com/homedetails/219-W-78th-St-APT-2F-New-York-NY-10024/2100775303_zpid/,http://www.zillow.com/homedetails/405-W-49th-St-APT-2W-New-York-NY-10019/2100776286_zpid/,http://www.zillow.com/homedetails/230-E-26th-St-APT-3A-New-York-NY-10010/2100776283_zpid/,http://www.zillow.com/homedetails/319-E-53rd-St-APT-2B-New-York-NY-10022/2104750345_zpid/,http://www.zillow.com/homedetails/53-Irving-Pl-APT-3K-New-York-NY-10003/2103128441_zpid/,http://www.zillow.com/homedetails/25-E-67th-St-APT-8D-New-York-NY-10065/2100777265_zpid/,http://www.zillow.com/homedetails/303-E-73rd-St-E-New-York-NY-10021/2100777278_zpid/,http://www.zillow.com/homedetails/422-E-81st-St-APT-4A-New-York-NY-10028/2111603077_zpid/,http://www.zillow.com/homedetails/445-W-49th-St-APT-3B-New-York-NY-10019/2106388119_zpid/,http://www.zillow.com/homedetails/203-E-121st-St-APT-901-New-York-NY-10035/2100777283_zpid/,http://www.zillow.com/homedetails/434-E-72nd-St-APT-2C-New-York-NY-10021/2120058527_zpid/
routable_link/_text,"9 E 129th St # 1, New York, NY10035","710 Riverside Dr APT 2C, New York, NY10031","413 E 84th St APT 8, New York, NY10028","324 Pleasant Ave APT 6E, New York, NY10035","217 Thompson St APT 6, New York, NY10012","340 W 47th St APT 4C, New York, NY10036","1356 1st Ave APT 5B, New York, NY10021","101 W 77th St APT 3C, New York, NY10024","111 W 74th St APT 2R, New York, NY10023","646 10th Ave APT 4B, New York, NY10036","76 Carmine St APT 4C, New York, NY10014","146 W 120th St APT 8, New York, NY10027","137 W 72nd St APT 4FE, New York, NY10023","178 Avenue B # 2, New York, NY10009","95 Wall St, New York, NY",...,"304 E 41st St APT 1107A, New York, NY10017","169 Avenue A APT 1, New York, NY10009","722 10th Ave APT 3A, New York, NY10019","200 W 70th St APT 11L3, New York, NY10023","219 W 78th St APT 2F, New York, NY10024","405 W 49th St APT 2W, New York, NY10019","230 E 26th St APT 3A, New York, NY10010","319 E 53rd St APT 2B, New York, NY10022","53 Irving Pl APT 3K, New York, NY10003","25 E 67th St APT 8D, New York, NY10065","303 E 73rd St # E, New York, NY10021","422 E 81st St APT 4A, New York, NY10028","445 W 49th St APT 3B, New York, NY10019","203 E 121st St APT 901, New York, NY10035","434 E 72nd St APT 2C, New York, NY10021"
routable_link/_title,"9 E 129th St # 1, New York, NY Real Estate","710 Riverside Dr APT 2C, New York, NY Real Estate","413 E 84th St APT 8, New York, NY Real Estate","324 Pleasant Ave APT 6E, New York, NY Real Estate","217 Thompson St APT 6, New York, NY Real Estate","340 W 47th St APT 4C, New York, NY Real Estate","1356 1st Ave APT 5B, New York, NY Real Estate","101 W 77th St APT 3C, New York, NY Real Estate","111 W 74th St APT 2R, New York, NY Real Estate","646 10th Ave APT 4B, New York, NY Real Estate","76 Carmine St APT 4C, New York, NY Real Estate","146 W 120th St APT 8, New York, NY Real Estate","137 W 72nd St APT 4FE, New York, NY Real Estate","178 Avenue B # 2, New York, NY Real Estate","95 Wall, Studio E1O Real Estate",...,"304 E 41st St APT 1107A, New York, NY Real Estate","169 Avenue A APT 1, New York, NY Real Estate","722 10th Ave APT 3A, New York, NY Real Estate","200 W 70th St APT 11L3, New York, NY Real Estate","219 W 78th St APT 2F, New York, NY Real Estate","405 W 49th St APT 2W, New York, NY Real Estate","230 E 26th St APT 3A, New York, NY Real Estate","319 E 53rd St APT 2B, New York, NY Real Estate","53 Irving Pl APT 3K, New York, NY Real Estate","25 E 67th St APT 8D, New York, NY Real Estate","303 E 73rd St # E, New York, NY Real Estate","422 E 81st St APT 4A, New York, NY Real Estate","445 W 49th St APT 3B, New York, NY Real Estate","203 E 121st St APT 901, New York, NY Real Estate","434 E 72nd St APT 2C, New York, NY Real Estate"
routable_link_numbers,9; 129; 1,710; 2,413; 84; 8,324; 6,217; 6,340; 47; 4,1356; 1; 5,101; 77; 3,111; 74; 2,646; 10; 4,76; 4,146; 120; 8,137; 72; 4,178; 2,95,...,304; 41; 1107,169; 1,722; 10; 3,200; 70; 11,219; 78; 2,405; 49; 2,230; 26; 3,319; 53; 2,53; 3,25; 67; 8,303; 73,422; 81; 4,445; 49; 3,203; 121; 901,434; 72; 2
listingtype_value,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,...,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent
pricelarge_value,"$1,750/mo","$3,000/mo","$2,300/mo","$2,500/mo","$2,800/mo","$2,490/mo","$2,750/mo","$2,150/mo","$2,875/mo","$2,225/mo","$2,450/mo","$1,800/mo","$2,850/mo","$2,700/mo","$3,000+/mo",...,"$2,200/mo","$2,195/mo","$2,995/mo","$1,895/mo","$2,493/mo","$2,925/mo","$2,940/mo","$2,170/mo","$2,300/mo","$2,600/mo","$2,265/mo","$2,150/mo","$2,195/mo","$1,795/mo","$2,150/mo"
pricelarge_value_prices,1.75e+03,3e+03,2.3e+03,2.5e+03,2.8e+03,2.49e+03,2.75e+03,2.15e+03,2.88e+03,2.22e+03,2.45e+03,1.8e+03,2.85e+03,2.7e+03,3e+03,...,2.2e+03,2.2e+03,3e+03,1.9e+03,2.49e+03,2.92e+03,2.94e+03,2.17e+03,2.3e+03,2.6e+03,2.26e+03,2.15e+03,2.2e+03,1.8e+03,2.15e+03
propertyinfo_value,1 bd • 1 ba,"2 bds • 2 ba • 1,016 sqft",Studio • 1 ba,2 bds • 1 ba,2 bds • 1 ba,1 bd • 1 ba,"1 bd • 1 ba • 496 sqft • 4,502 sqft lot • Built 1900",Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba,Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba • 700 sqft,1 bd • 1 ba,Studio • 1 ba • 487 sqft,...,Studio • 1 ba,Studio • 1 ba,1 bd • 1 ba • 475 sqft • Built 1900,Studio • 1 ba,1 bd • 1 ba • 500 sqft,2 bds • 1 ba,2 bds • 1 ba,Studio • 1 ba,Studio • 1 ba • 400 sqft,Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba,Studio • 1 ba,Studio • 1 ba • 550 sqft,1 bd • 1 ba
propertyinfo_value_numbers,1; 1,2; 2; 1016,1,2; 1,2; 1,1; 1,1; 1; 496; 4502; 1900,1,1; 1,1; 1,1,1; 1,1; 1; 700,1; 1,1; 487,...,1,1,1; 1; 475; 1900,1,1; 1; 500,2; 1,2; 1,1,1; 400,1,1; 1,1; 1,1,1; 550,1; 1
fineprint_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fineprint_value_numbers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tozcount_number,48,1,2,2,3,6,6,6,6,6,7,9,9,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tozfresh_value,minutes ago,hour ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,Updated today,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tablegrouped_values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tablegrouped_values_prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
_PAGE_NUMBER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...,19,19,20,20,20,20,20,20,20,20,20,20,20,20,20
Baths,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Beds,1,2,Studio,2,2,1,1,Studio,1,1,Studio,1,1,1,Studio,...,Studio,Studio,1,Studio,1,2,2,Studio,Studio,Studio,1,1,Studio,Studio,1
Sqft,NaN,"1,016",NaN,NaN,NaN,NaN,496,NaN,NaN,NaN,NaN,NaN,700,NaN,487,...,NaN,NaN,475,NaN,500,NaN,NaN,NaN,400,NaN,NaN,NaN,NaN,550,NaN

In [31]:
# parse out zip, floor

def parse_addy(r):
    so_zip = re.search(', NY(\d+)', r) # NY打头后面的数字是邮编
    so_flr = re.search('(?:APT|#)\s+(\d+)[A-Z]+,', r) # APT后面跟随的数字是楼层
    if so_zip:
        zipc = so_zip.group(1)
    else:
        zipc = np.nan
    if so_flr:
        flr = so_flr.group(1)
    else:
        flr = np.nan
    return pd.Series({'Zip':zipc, 'Floor': flr})

In [32]:
flrzip = sujnd['routable_link/_text'].apply(parse_addy)

In [33]:
flrzip

    Floor    Zip
2     NaN  10035
3       2  10031
4     NaN  10028
5       6  10035
7     NaN  10012
10      4  10036
11      5  10021
12      3  10024
13      2  10023
17      4  10036
18      4  10014
19    NaN  10027
20      4  10023
21    NaN  10009
23    NaN    NaN
24    NaN  10002
27    NaN  10009
29    NaN  10002
30    NaN  10009
33      2  10002
36      2  10013
38    NaN  10002
40    NaN  10004
42      4  10023
44      1  10024
45      3  10024
46      3  10026
47      4  10019
48    NaN  10065
49      6  10037
..    ...    ...
450     2  10032
451     2  10032
452     1  10029
453   NaN  10017
454     3  10075
457     9  10025
458   NaN  10021
459     5  10075
460   NaN  10003
461   NaN    NaN
462   NaN    NaN
464    20  10016
466     2  10011
467   NaN    NaN
468   NaN    NaN
470  1107  10017
471   NaN  10009
475     3  10019
477   NaN  10023
479     2  10024
483     2  10019
484     3  10010
485     2  10022
486     3  10003
487     8  10065
490   NaN  10021
492     4  10028
496     3  10019
497   NaN  10035
499     2  10021

[333 rows x 2 columns]

In [34]:
len(flrzip[~flrzip['Floor'].isnull()])

164

In [35]:
len(flrzip[~flrzip['Zip'].isnull()])

320

In [36]:
suf = sujnd.join(flrzip)

In [37]:
suf.T

,2,3,4,5,7,10,11,12,13,17,18,19,20,21,23,...,470,471,475,477,479,483,484,485,486,487,490,492,496,497,499
routablemask_link,http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,http://www.zillow.com/homedetails/646-10th-Ave-APT-4B-New-York-NY-10036/2114397534_zpid/,http://www.zillow.com/homedetails/76-Carmine-St-APT-4C-New-York-NY-10014/2110813540_zpid/,http://www.zillow.com/homedetails/146-W-120th-St-APT-8-New-York-NY-10027/2100762986_zpid/,http://www.zillow.com/homedetails/137-W-72nd-St-APT-4FE-New-York-NY-10023/2105480982_zpid/,http://www.zillow.com/homedetails/178-Avenue-B-2-New-York-NY-10009/2100763265_zpid/,http://www.zillow.com/homedetails/95-Wall-St-72791-New-York-NY-10005/2103168440_zpid/,...,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/,http://www.zillow.com/homedetails/169-Avenue-A-APT-1-New-York-NY-10009/2105208117_zpid/,http://www.zillow.com/homedetails/722-10th-Ave-APT-3A-New-York-NY-10019/2126268388_zpid/,http://www.zillow.com/homedetails/200-W-70th-St-APT-11L3-New-York-NY-10023/2100774851_zpid/,http://www.zillow.com/homedetails/219-W-78th-St-APT-2F-New-York-NY-10024/2100775303_zpid/,http://www.zillow.com/homedetails/405-W-49th-St-APT-2W-New-York-NY-10019/2100776286_zpid/,http://www.zillow.com/homedetails/230-E-26th-St-APT-3A-New-York-NY-10010/2100776283_zpid/,http://www.zillow.com/homedetails/319-E-53rd-St-APT-2B-New-York-NY-10022/2104750345_zpid/,http://www.zillow.com/homedetails/53-Irving-Pl-APT-3K-New-York-NY-10003/2103128441_zpid/,http://www.zillow.com/homedetails/25-E-67th-St-APT-8D-New-York-NY-10065/2100777265_zpid/,http://www.zillow.com/homedetails/303-E-73rd-St-E-New-York-NY-10021/2100777278_zpid/,http://www.zillow.com/homedetails/422-E-81st-St-APT-4A-New-York-NY-10028/2111603077_zpid/,http://www.zillow.com/homedetails/445-W-49th-St-APT-3B-New-York-NY-10019/2106388119_zpid/,http://www.zillow.com/homedetails/203-E-121st-St-APT-901-New-York-NY-10035/2100777283_zpid/,http://www.zillow.com/homedetails/434-E-72nd-St-APT-2C-New-York-NY-10021/2120058527_zpid/
routablemask_link/_text,NaN,9 photos,5 photos,7 photos,NaN,NaN,9 photos,4 photos,6 photos,NaN,4 photos,6 photos,10 photos,6 photos,17 photos,...,5 photos,8 photos,5 photos,4 photos,6 photos,5 photos,6 photos,5 photos,6 photos,NaN,5 photos,4 photos,4 photos,4 photos,1 photo
routablemask_link/_title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
routablemask_link_numbers,NaN,9,5,7,NaN,NaN,9,4,6,NaN,4,6,10,6,17,...,5,8,5,4,6,5,6,5,6,NaN,5,4,4,4,1
routablemask_content,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
imagebadge_value,NaN,9 photos,5 photos,7 photos,NaN,NaN,9 photos,4 photos,6 photos,NaN,4 photos,6 photos,10 photos,6 photos,17 photos,...,5 photos,8 photos,5 photos,4 photos,6 photos,5 photos,6 photos,5 photos,6 photos,NaN,5 photos,4 photos,4 photos,4 photos,1 photo
imagebadge_value_numbers,NaN,9,5,7,NaN,NaN,9,4,6,NaN,4,6,10,6,17,...,5,8,5,4,6,5,6,5,6,NaN,5,4,4,4,1
routable_link,http://www.zillow.com/homedetails/9-E-129th-St-1-New-York-NY-10035/2100761096_zpid/,http://www.zillow.com/homedetails/710-Riverside-Dr-APT-2C-New-York-NY-10031/124451755_zpid/,http://www.zillow.com/homedetails/413-E-84th-St-APT-8-New-York-NY-10028/2100761260_zpid/,http://www.zillow.com/homedetails/324-Pleasant-Ave-APT-6E-New-York-NY-10035/2100761258_zpid/,http://www.zillow.com/homedetails/217-Thompson-St-APT-6-New-York-NY-10012/2100761371_zpid/,http://www.zillow.com/homedetails/340-W-47th-St-APT-4C-New-York-NY-10036/2108861613_zpid/,http://www.zillow.com/homedetails/1356-1st-Ave-APT-5B-New-York-NY-10021/31539199_zpid/,http://www.zillow.com/homedetails/101-W-77th-St-APT-3C-New-York-NY-10024/2114511658_zpid/,http://www.zillow.com/homedetails/111-W-74th-St-APT-2R-New-York-NY-10023/2123304010_zpid/,http://www.zillow.com/homedetails/646-10th-Ave-APT-4B-New-York-NY-10036/2114397534_zpid/,http://www.zillow.com/homedetails/76-Carmine-St-APT-4C-New-York-NY-10014/2110813540_zpid/,http://www.zillow.com/homedetails/146-W-120th-St-APT-8-New-York-NY-10027/2100762986_zpid/,http://www.zillow.com/homedetails/137-W-72nd-St-APT-4FE-New-York-NY-10023/2105480982_zpid/,http://www.zillow.com/homedetails/178-Avenue-B-2-New-York-NY-10009/2100763265_zpid/,http://www.zillow.com/homedetails/95-Wall-St-72791-New-York-NY-10005/2103168440_zpid/,...,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/,http://www.zillow.com/homedetails/169-Avenue-A-APT-1-New-York-NY-10009/2105208117_zpid/,http://www.zillow.com/homedetails/722-10th-Ave-APT-3A-New-York-NY-10019/2126268388_zpid/,http://www.zillow.com/homedetails/200-W-70th-St-APT-11L3-New-York-NY-10023/2100774851_zpid/,http://www.zillow.com/homedetails/219-W-78th-St-APT-2F-New-York-NY-10024/2100775303_zpid/,http://www.zillow.com/homedetails/405-W-49th-St-APT-2W-New-York-NY-10019/2100776286_zpid/,http://www.zillow.com/homedetails/230-E-26th-St-APT-3A-New-York-NY-10010/2100776283_zpid/,http://www.zillow.com/homedetails/319-E-53rd-St-APT-2B-New-York-NY-10022/2104750345_zpid/,http://www.zillow.com/homedetails/53-Irving-Pl-APT-3K-New-York-NY-10003/2103128441_zpid/,http://www.zillow.com/homedetails/25-E-67th-St-APT-8D-New-York-NY-10065/2100777265_zpid/,http://www.zillow.com/homedetails/303-E-73rd-St-E-New-York-NY-10021/2100777278_zpid/,http://www.zillow.com/homedetails/422-E-81st-St-APT-4A-New-York-NY-10028/2111603077_zpid/,http://www.zillow.com/homedetails/445-W-49th-St-APT-3B-New-York-NY-10019/2106388119_zpid/,http://www.zillow.com/homedetails/203-E-121st-St-APT-901-New-York-NY-10035/2100777283_zpid/,http://www.zillow.com/homedetails/434-E-72nd-St-APT-2C-New-York-NY-10021/2120058527_zpid/
routable_link/_text,"9 E 129th St # 1, New York, NY10035","710 Riverside Dr APT 2C, New York, NY10031","413 E 84th St APT 8, New York, NY10028","324 Pleasant Ave APT 6E, New York, NY10035","217 Thompson St APT 6, New York, NY10012","340 W 47th St APT 4C, New York, NY10036","1356 1st Ave APT 5B, New York, NY10021","101 W 77th St APT 3C, New York, NY10024","111 W 74th St APT 2R, New York, NY10023","646 10th Ave APT 4B, New York, NY10036","76 Carmine St APT 4C, New York, NY10014","146 W 120th St APT 8, New York, NY10027","137 W 72nd St APT 4FE, New York, NY10023","178 Avenue B # 2, New York, NY10009","95 Wall St, New York, NY",...,"304 E 41st St APT 1107A, New York, NY10017","169 Avenue A APT 1, New York, NY10009","722 10th Ave APT 3A, New York, NY10019","200 W 70th St APT 11L3, New York, NY10023","219 W 78th St APT 2F, New York, NY10024","405 W 49th St APT 2W, New York, NY10019","230 E 26th St APT 3A, New York, NY10010","319 E 53rd St APT 2B, New York, NY10022","53 Irving Pl APT 3K, New York, NY10003","25 E 67th St APT 8D, New York, NY10065","303 E 73rd St # E, New York, NY10021","422 E 81st St APT 4A, New York, NY10028","445 W 49th St APT 3B, New York, NY10019","203 E 121st St APT 901, New York, NY10035","434 E 72nd St APT 2C, New York, NY10021"
routable_link/_title,"9 E 129th St # 1, New York, NY Real Estate","710 Riverside Dr APT 2C, New York, NY Real Estate","413 E 84th St APT 8, New York, NY Real Estate","324 Pleasant Ave APT 6E, New York, NY Real Estate","217 Thompson St APT 6, New York, NY Real Estate","340 W 47th St APT 4C, New York, NY Real Estate","1356 1st Ave APT 5B, New York, NY Real Estate","101 W 77th St APT 3C, New York, NY Real Estate","111 W 74th St APT 2R, New York, NY Real Estate","646 10th Ave APT 4B, New York, NY Real Estate","76 Carmine St APT 4C, New York, NY Real Estate","146 W 120th St APT 8, New York, NY Real Estate","137 W 72nd St APT 4FE, New York, NY Real Estate","178 Avenue B # 2, New York, NY Real Estate","95 Wall, Studio E1O Real Estate",...,"304 E 41st St APT 1107A, New York, NY Real Estate","169 Avenue A APT 1, New York, NY Real Estate","722 10th Ave APT 3A, New York, NY Real Estate","200 W 70th St APT 11L3, New York, NY Real Estate","219 W 78th St APT 2F, New York, NY Real Estate","405 W 49th St APT 2W, New York, NY Real Estate","230 E 26th St APT 3A, New York, NY Real Estate","319 E 53rd St APT 2B, New York, NY Real Estate","53 Irving Pl APT 3K, New York, NY Real Estate","25 E 67th St APT 8D, New York, NY Real Estate","303 E 73rd St # E, New York, NY Real Estate","422 E 81st St APT 4A, New York, NY Real Estate","445 W 49th St APT 3B, New York, NY Real Estate","203 E 121st St APT 901, New York, NY Real Estate","434 E 72nd St APT 2C, New York, NY Real Estate"
routable_link_numbers,9; 129; 1,710; 2,413; 84; 8,324; 6,217; 6,340; 47; 4,1356; 1; 5,101; 77; 3,111; 74; 2,646; 10; 4,76; 4,146; 120; 8,137; 72; 4,178; 2,95,...,304; 41; 1107,169; 1,722; 10; 3,200; 70; 11,219; 78; 2,405; 49; 2,230; 26; 3,319; 53; 2,53; 3,25; 67; 8,303; 73,422; 81; 4,445; 49; 3,203; 121; 901,434; 72; 2
listingtype_value,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,...,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent,Apartment For Rent
pricelarge_value,"$1,750/mo","$3,000/mo","$2,300/mo","$2,500/mo","$2,800/mo","$2,490/mo","$2,750/mo","$2,150/mo","$2,875/mo","$2,225/mo","$2,450/mo","$1,800/mo","$2,850/mo","$2,700/mo","$3,000+/mo",...,"$2,200/mo","$2,195/mo","$2,995/mo","$1,895/mo","$2,493/mo","$2,925/mo","$2,940/mo","$2,170/mo","$2,300/mo","$2,600/mo","$2,265/mo","$2,150/mo","$2,195/mo","$1,795/mo","$2,150/mo"
pricelarge_value_prices,1.75e+03,3e+03,2.3e+03,2.5e+03,2.8e+03,2.49e+03,2.75e+03,2.15e+03,2.88e+03,2.22e+03,2.45e+03,1.8e+03,2.85e+03,2.7e+03,3e+03,...,2.2e+03,2.2e+03,3e+03,1.9e+03,2.49e+03,2.92e+03,2.94e+03,2.17e+03,2.3e+03,2.6e+03,2.26e+03,2.15e+03,2.2e+03,1.8e+03,2.15e+03
propertyinfo_value,1 bd • 1 ba,"2 bds • 2 ba • 1,016 sqft",Studio • 1 ba,2 bds • 1 ba,2 bds • 1 ba,1 bd • 1 ba,"1 bd • 1 ba • 496 sqft • 4,502 sqft lot • Built 1900",Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba,Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba • 700 sqft,1 bd • 1 ba,Studio • 1 ba • 487 sqft,...,Studio • 1 ba,Studio • 1 ba,1 bd • 1 ba • 475 sqft • Built 1900,Studio • 1 ba,1 bd • 1 ba • 500 sqft,2 bds • 1 ba,2 bds • 1 ba,Studio • 1 ba,Studio • 1 ba • 400 sqft,Studio • 1 ba,1 bd • 1 ba,1 bd • 1 ba,Studio • 1 ba,Studio • 1 ba • 550 sqft,1 bd • 1 ba
propertyinfo_value_numbers,1; 1,2; 2; 1016,1,2; 1,2; 1,1; 1,1; 1; 496; 4502; 1900,1,1; 1,1; 1,1,1; 1,1; 1; 700,1; 1,1; 487,...,1,1,1; 1; 475; 1900,1,1; 1; 500,2; 1,2; 1,1,1; 400,1,1; 1,1; 1,1,1; 550,1; 1
fineprint_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fineprint_value_numbers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tozcount_number,48,1,2,2,3,6,6,6,6,6,7,9,9,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tozfresh_value,minutes ago,hour ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,hours ago,Updated today,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tablegrouped_values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tablegrouped_values_prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
_PAGE_NUMBER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...,19,19,20,20,20,20,20,20,20,20,20,20,20,20,20
Baths,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Beds,1,2,Studio,2,2,1,1,Studio,1,1,Studio,1,1,1,Studio,...,Studio,Studio,1,Studio,1,2,2,Studio,Studio,Studio,1,1,Studio,Studio,1
Sqft,NaN,"1,016",NaN,NaN,NaN,NaN,496,NaN,NaN,NaN,NaN,NaN,700,NaN,487,...,NaN,NaN,475,NaN,500,NaN,NaN,NaN,400,NaN,NaN,NaN,NaN,550,NaN
Floor,NaN,2,NaN,6,NaN,4,5,3,2,4,4,NaN,4,NaN,NaN,...,1107,NaN,3,NaN,2,2,3,2,3,8,NaN,4,3,NaN,2
Zip,10035,10031,10028,10035,10012,10036,10021,10024,10023,10036,10014,10027,10023,10009,NaN,...,10017,10009,10019,10023,10024,10019,10010,10022,10003,10065,10021,10028,10019,10035,10021

In [38]:
# we'll reduce the data down to the columns of interest 只剩下关心的字段
sudf = suf[['pricelarge_value_prices','Beds','Baths','Sqft','Floor','Zip']]
sudf.head()

   pricelarge_value_prices    Beds Baths   Sqft Floor    Zip
2                   1750.0       1     1    NaN   NaN  10035
3                   3000.0       2     2  1,016     2  10031
4                   2300.0  Studio     1    NaN   NaN  10028
5                   2500.0       2     1    NaN     6  10035
7                   2800.0       2     1    NaN   NaN  10012

In [39]:
# we'll also clean up the weird column name 将列名pricelarge_value_prices替换为Rent
sudf.rename(columns={'pricelarge_value_prices':'Rent'}, inplace=True)
sudf.head()

/Users/palance/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:2746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

     Rent    Beds Baths   Sqft Floor    Zip
2  1750.0       1     1    NaN   NaN  10035
3  3000.0       2     2  1,016     2  10031
4  2300.0  Studio     1    NaN   NaN  10028
5  2500.0       2     1    NaN     6  10035
7  2800.0       2     1    NaN   NaN  10012

In [40]:
sudf.reset_index(drop=True, inplace=True)

In [41]:
sudf.head()

     Rent    Beds Baths   Sqft Floor    Zip
0  1750.0       1     1    NaN   NaN  10035
1  3000.0       2     2  1,016     2  10031
2  2300.0  Studio     1    NaN   NaN  10028
3  2500.0       2     1    NaN     6  10035
4  2800.0       2     1    NaN   NaN  10012

## 分析数据

In [42]:
sudf.describe() # 输出数据条数、平均值、标准差、最值等

           Rent
count   333.000
mean   2492.628
std     366.882
min    1500.000
25%    2200.000
50%    2525.000
75%    2800.000
max    3000.000

In [43]:
# we'll replace 'Studio' with 0 where present 将Beds字段为Studio的值替换为0
sudf.loc[:,'Beds'] = sudf['Beds'].map(lambda x: 0 if 'Studio' in x else x)

/Users/palance/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [44]:
sudf.head()

     Rent Beds Baths   Sqft Floor    Zip
0  1750.0    1     1    NaN   NaN  10035
1  3000.0    2     2  1,016     2  10031
2  2300.0    0     1    NaN   NaN  10028
3  2500.0    2     1    NaN     6  10035
4  2800.0    2     1    NaN   NaN  10012

In [45]:
# we're not getting stats on 'Beds','Baths', and 'Floor' because of the datatype
sudf.info() # 查看各字段的数据类型

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 6 columns):
Rent     333 non-null float64
Beds     333 non-null object
Baths    333 non-null object
Sqft     108 non-null object
Floor    164 non-null object
Zip      320 non-null object
dtypes: float64(1), object(5)
memory usage: 15.7+ KB

In [46]:
# let's fix the datatype for the columns 将各字段转成数字
sudf.loc[:,'Rent'] = sudf['Rent'].astype(int)
sudf.loc[:,'Beds'] = sudf['Beds'].astype(int)

# half baths require a float
sudf.loc[:,'Baths'] = sudf['Baths'].astype(float)

# with NaNs we need float, but we have to replace commas first
sudf.loc[:,'Sqft'] = sudf['Sqft'].str.replace(',','')

sudf.loc[:,'Sqft'] = sudf['Sqft'].astype(float)
sudf.loc[:,'Floor'] = sudf['Floor'].astype(float)

/Users/palance/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [47]:
sudf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 6 columns):
Rent     333 non-null int64
Beds     333 non-null int64
Baths    333 non-null float64
Sqft     108 non-null float64
Floor    164 non-null float64
Zip      320 non-null object
dtypes: float64(3), int64(2), object(1)
memory usage: 15.7+ KB

In [48]:
sudf.describe()

           Rent     Beds    Baths      Sqft     Floor
count   333.000  333.000  333.000   108.000   164.000
mean   2492.628    0.820    1.008   528.981    11.201
std     366.882    0.718    0.082   133.050    86.178
min    1500.000    0.000    1.000   280.000     1.000
25%    2200.000    0.000    1.000   447.500     2.000
50%    2525.000    1.000    1.000   512.000     4.000
75%    2800.000    1.000    1.000   600.000     5.000
max    3000.000    3.000    2.000  1090.000  1107.000

In [49]:
sudf[sudf['Floor']>5] # 条件查询

     Rent  Beds  Baths   Sqft   Floor    Zip
3    2500     2    1.0    NaN     6.0  10035
29   1815     1    1.0  596.0     6.0  10037
43   1815     1    1.0  596.0     6.0  10037
44   2950     0    1.0    NaN     7.0  10036
59   3000     0    1.0  541.0     9.0  10013
74   2295     1    1.0    NaN    11.0  10002
77   2999     1    1.0    NaN    12.0  10012
87   2350     2    1.0  550.0     6.0  10003
93   2550     0    1.0  425.0    14.0  10006
110  2400     0    1.0  550.0     8.0  10002
158  2299     0    1.0    NaN     8.0  10006
165  2788     1    1.0  514.0     9.0  10006
166  2950     1    1.0  530.0    10.0  10002
179  2595     0    1.0  438.0     7.0  10002
183  2250     1    1.0    NaN     6.0  10009
190  2950     1    1.0  550.0     6.0  10280
193  2995     2    1.0  550.0     6.0  10038
198  2800     0    1.0  687.0    14.0  10038
209  2950     1    1.0  522.0    16.0  10017
213  2995     0    1.0  583.0    11.0  10004
221  2525     0    1.0    NaN    16.0  10038
223  2650     0    1.0  452.0    32.0  10005
232  2699     0    1.0  500.0     7.0  10003
233  2000     0    1.0    NaN     7.0  10038
245  2600     0    1.0  496.0     9.0  10038
246  2545     0    1.0  620.0    14.0  10280
290  3000     1    1.0  400.0     9.0  10017
296  2975     0    1.0    NaN     9.0  10001
297  2350     0    1.0  500.0    10.0  10016
308  2500     0    1.0  540.0     9.0  10025
314  2500     0    1.0  485.0    20.0  10016
318  2200     0    1.0    NaN  1107.0  10017
327  2600     0    1.0    NaN     8.0  10065

In [50]:
suf[suf['Floor'].astype(float)>25].T

,327,470
routablemask_link,http://www.zillow.com/homedetails/75-Wall-St-APT-32H-New-York-NY-10005/89330333_zpid/,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/
routablemask_link/_text,10 photos,5 photos
routablemask_link/_title,NaN,NaN
routablemask_link_numbers,10,5
routablemask_content,NaN,NaN
imagebadge_value,10 photos,5 photos
imagebadge_value_numbers,10,5
routable_link,http://www.zillow.com/homedetails/75-Wall-St-APT-32H-New-York-NY-10005/89330333_zpid/,http://www.zillow.com/homedetails/304-E-41st-St-APT-1107A-New-York-NY-10017/2100774366_zpid/
routable_link/_text,"75 Wall St APT 32H, New York, NY10005","304 E 41st St APT 1107A, New York, NY10017"
routable_link/_title,"75 Wall St APT 32H, New York, NY Real Estate","304 E 41st St APT 1107A, New York, NY Real Estate"
routable_link_numbers,75; 32,304; 41; 1107
listingtype_value,Apartment For Rent,Apartment For Rent
pricelarge_value,"$2,650/mo","$2,200/mo"
pricelarge_value_prices,2.65e+03,2.2e+03
propertyinfo_value,Studio • 1 ba • 452 sqft • 452 sqft lot • Built 1987,Studio • 1 ba
propertyinfo_value_numbers,1; 452; 452; 1987,1
fineprint_value,NaN,NaN
fineprint_value_numbers,NaN,NaN
tozcount_number,NaN,NaN
tozfresh_value,NaN,NaN
tablegrouped_values,NaN,NaN
tablegrouped_values_prices,NaN,NaN
_PAGE_NUMBER,14,19
Baths,1,1
Beds,Studio,Studio
Sqft,452,NaN
Floor,32,1107
Zip,10005,10017

In [51]:
# index 318 was the problem listing, so we'll drop it 第318条记录的Floor=1107.0，是个垃圾数据，因此删除
sudf = sudf.drop([318])

In [52]:
sudf.describe()

           Rent     Beds    Baths      Sqft    Floor
count   332.000  332.000  332.000   108.000  163.000
mean   2493.509    0.822    1.008   528.981    4.479
std     367.083    0.718    0.082   133.050    3.861
min    1500.000    0.000    1.000   280.000    1.000
25%    2200.000    0.000    1.000   447.500    2.000
50%    2527.500    1.000    1.000   512.000    4.000
75%    2800.000    1.000    1.000   600.000    5.000
max    3000.000    3.000    2.000  1090.000   32.000

In [53]:
sudf.pivot_table('Rent', 'Zip', 'Beds', aggfunc='mean') # 根据Zip和Beds数量统计租金平均值

Beds          0         1         2       3
Zip
10001  2737.500       NaN       NaN     NaN
10002  2283.438  2422.513  2792.647     NaN
10003  2109.889  2487.812  2525.000     NaN
10004  2798.750  2850.000       NaN     NaN
10005  2516.000       NaN       NaN     NaN
10006  2611.000  2788.000       NaN     NaN
10009  2200.909  2568.441  2530.000     NaN
10010       NaN  2299.000  2940.000     NaN
10011  2774.667  2852.000  2595.000     NaN
10012  2547.000  2744.909  2581.667     NaN
10013  2709.286  2584.444  2650.000     NaN
10014  2450.000       NaN       NaN     NaN
10016  2615.000  2450.000       NaN     NaN
10017       NaN  2733.333       NaN     NaN
10019  2195.000  2661.667  2925.000     NaN
10021  1900.000  2388.333  2500.000     NaN
10022  2170.000       NaN       NaN     NaN
10023  2165.000  2773.333       NaN     NaN
10024  2322.500  2621.500       NaN     NaN
10025  2500.000       NaN       NaN     NaN
10026       NaN  2800.000       NaN     NaN
10027       NaN  1850.000       NaN     NaN
10028  2100.000  2333.333       NaN     NaN
10029  1597.500  2097.500  2650.000     NaN
10031       NaN       NaN  2531.250  2700.0
10032       NaN       NaN  2047.500  2350.0
10033       NaN  1825.000       NaN     NaN
10034       NaN       NaN  1900.000     NaN
10035  1795.000  1948.333  2350.000     NaN
10036  2950.000  2357.500  2700.000     NaN
10037       NaN  1815.000       NaN     NaN
10038  2602.222  2395.000  2647.500     NaN
10040       NaN  1550.000       NaN     NaN
10065  2547.500  2131.667       NaN     NaN
10075  2000.000  2625.000  2695.000     NaN
10128       NaN       NaN  2900.000     NaN
10280  2695.000  2972.500       NaN     NaN
11101       NaN       NaN  2393.000     NaN
11206       NaN       NaN  2600.000     NaN
11209       NaN       NaN  1995.000     NaN
11229       NaN  2595.000       NaN     NaN

In [54]:
sudf.pivot_table('Rent', 'Zip', 'Beds', aggfunc='count') # 根据Zip和Beds统计房源个数

Beds      0     1     2    3
Zip
10001   2.0   NaN   NaN  NaN
10002  16.0  39.0  17.0  NaN
10003   9.0  16.0   2.0  NaN
10004   4.0   1.0   NaN  NaN
10005   4.0   NaN   NaN  NaN
10006   4.0   1.0   NaN  NaN
10009  11.0  34.0   8.0  NaN
10010   NaN   1.0   1.0  NaN
10011   3.0   1.0   1.0  NaN
10012   5.0  11.0   3.0  NaN
10013   7.0   9.0   2.0  NaN
10014   1.0   NaN   NaN  NaN
10016   3.0   1.0   NaN  NaN
10017   NaN   3.0   NaN  NaN
10019   1.0   3.0   1.0  NaN
10021   1.0   3.0   1.0  NaN
10022   1.0   NaN   NaN  NaN
10023   3.0   3.0   NaN  NaN
10024   6.0   2.0   NaN  NaN
10025   1.0   NaN   NaN  NaN
10026   NaN   2.0   NaN  NaN
10027   NaN   2.0   NaN  NaN
10028   2.0   3.0   NaN  NaN
10029   2.0   4.0   1.0  NaN
10031   NaN   NaN   4.0  1.0
10032   NaN   NaN   2.0  1.0
10033   NaN   1.0   NaN  NaN
10034   NaN   NaN   1.0  NaN
10035   1.0   3.0   2.0  NaN
10036   1.0   2.0   1.0  NaN
10037   NaN   2.0   NaN  NaN
10038   9.0   1.0   2.0  NaN
10040   NaN   1.0   NaN  NaN
10065   2.0   3.0   NaN  NaN
10075   2.0   2.0   1.0  NaN
10128   NaN   NaN   2.0  NaN
10280   4.0   2.0   NaN  NaN
11101   NaN   NaN   1.0  NaN
11206   NaN   NaN   1.0  NaN
11209   NaN   NaN   1.0  NaN
11229   NaN   1.0   NaN  NaN

## Create a Property Heatmap

In [55]:
su_lt_two = sudf[sudf['Beds']<2]

In [56]:
# 按照https://github.com/python-visualization/folium安装模块
# import folium
# map = folium.Map(location=[40.748817, -73.985428], zoom_start=13) # 传入经纬度和缩放比例
# map

In [57]:
# map = folium.Map(location=[40.748817, -73.985428], zoom_start=13)
# folium.Marker([40.748817, -73.985428], popup='Solar Power Station').add_to(map)
# map.save('nyc.html')

In [58]:

# map.geo_json(geo_path=r'../Datasets/nyc.json', data=su_lt_two,
#              columns=['Zip', 'Rent'],
#              key_on='feature.properties.postalCode',
#              threshold_scale=[1700.00, 1900.00, 2100.00, 2300.00, 2500.00, 2750.00],
#              fill_color='YlOrRd', fill_opacity=0.7, line_opacity=0.2,
#              legend_name='Rent (%)',
#               reset=True)
# map.create_map(path='nyc.html')

In [59]:
su_lt_two

     Rent  Beds  Baths   Sqft  Floor    Zip
0    1750     1    1.0    NaN    NaN  10035
2    2300     0    1.0    NaN    NaN  10028
5    2490     1    1.0    NaN    4.0  10036
6    2750     1    1.0  496.0    5.0  10021
7    2150     0    1.0    NaN    3.0  10024
8    2875     1    1.0    NaN    2.0  10023
9    2225     1    1.0    NaN    4.0  10036
10   2450     0    1.0    NaN    4.0  10014
11   1800     1    1.0    NaN    NaN  10027
12   2850     1    1.0  700.0    4.0  10023
13   2700     1    1.0    NaN    NaN  10009
14   3000     0    1.0  487.0    NaN    NaN
16   2700     1    1.0  525.0    NaN  10009
18   2850     1    1.0    NaN    NaN  10009
19   2199     1    1.0    NaN    2.0  10002
20   2895     0    1.0    NaN    2.0  10013
21   2200     1    1.0    NaN    NaN  10002
22   2600     0    1.0  406.0    NaN  10004
23   2300     0    1.0  350.0    4.0  10023
24   2400     0    1.0    NaN    1.0  10024
25   2195     0    1.0  400.0    3.0  10024
26   2800     1    1.0  600.0    3.0  10026
27   2495     1    1.0    NaN    4.0  10019
28   1900     1    1.0    NaN    NaN  10065
29   1815     1    1.0  596.0    6.0  10037
30   2700     1    1.0  525.0    NaN  10009
32   2850     1    1.0    NaN    NaN  10009
33   2199     1    1.0    NaN    2.0  10002
34   2895     0    1.0    NaN    2.0  10013
35   2200     1    1.0    NaN    NaN  10002
..    ...   ...    ...    ...    ...    ...
294  1900     0    1.0    NaN    2.0  10021
295  2925     0    1.0    NaN    5.0  10011
296  2975     0    1.0    NaN    9.0  10001
297  2350     0    1.0  500.0   10.0  10016
299  2449     0    1.0    NaN    NaN  10011
300  2852     1    1.0    NaN    5.0  10011
302  2885     0    1.0  432.0    NaN    NaN
305  2095     1    1.0    NaN    1.0  10029
306  2250     1    1.0    NaN    NaN  10017
307  2450     1    1.0    NaN    3.0  10075
308  2500     0    1.0  540.0    9.0  10025
310  1800     0    1.0    NaN    5.0  10075
311  2495     1    1.0    NaN    NaN  10003
312  2950     0    1.0    NaN    NaN    NaN
313  2950     0    1.0    NaN    NaN    NaN
314  2500     0    1.0  485.0   20.0  10016
316  2965     0    1.0  522.0    NaN    NaN
317  2815     0    1.0  480.0    NaN    NaN
319  2195     0    1.0    NaN    NaN  10009
320  2995     1    1.0  475.0    3.0  10019
321  1895     0    1.0    NaN    NaN  10023
322  2493     1    1.0  500.0    2.0  10024
325  2170     0    1.0    NaN    2.0  10022
326  2300     0    1.0  400.0    3.0  10003
327  2600     0    1.0    NaN    8.0  10065
328  2265     1    1.0    NaN    NaN  10021
329  2150     1    1.0    NaN    4.0  10028
330  2195     0    1.0    NaN    3.0  10019
331  1795     0    1.0  550.0    NaN  10035
332  2150     1    1.0    NaN    2.0  10021

[275 rows x 6 columns]

## Regression Modeling

In [61]:
su_lt_two.sort_values('Zip')

     Rent  Beds  Baths   Sqft  Floor    Zip
257  2500     0    1.0    NaN    4.0  10001
296  2975     0    1.0    NaN    9.0  10001
74   2295     1    1.0    NaN   11.0  10002
137  1950     0    1.0    NaN    5.0  10002
72   2675     1    1.0  475.0    NaN  10002
71   2595     1    1.0    NaN    NaN  10002
70   2350     1    1.0  326.0    2.0  10002
76   2350     1    1.0    NaN    NaN  10002
138  2250     0    1.0  500.0    NaN  10002
64   2050     1    1.0    NaN    NaN  10002
61   2550     1    1.0  650.0    4.0  10002
143  1600     1    1.0  300.0    NaN  10002
148  1995     0    1.0    NaN    NaN  10002
55   2995     1    1.0  650.0    4.0  10002
52   2150     0    1.0  450.0    NaN  10002
67   2530     1    1.0    NaN    3.0  10002
242  2400     1    1.0  422.0    3.0  10002
116  2650     1    1.0    NaN    NaN  10002
81   1995     1    1.0    NaN    NaN  10002
110  2400     0    1.0  550.0    8.0  10002
118  2700     1    1.0    NaN    NaN  10002
119  1750     0    1.0    NaN    3.0  10002
106  2400     0    1.0  500.0    NaN  10002
105  2295     1    1.0    NaN    1.0  10002
104  2595     1    1.0    NaN    2.0  10002
135  2600     1    1.0    NaN    NaN  10002
103  2695     1    1.0    NaN    4.0  10002
101  2050     1    1.0    NaN    NaN  10002
98   2800     1    1.0  750.0    1.0  10002
130  2975     1    1.0    NaN    4.0  10002
..    ...   ...    ...    ...    ...    ...
288  1550     1    1.0    NaN    5.0  10040
42   1900     1    1.0    NaN    NaN  10065
327  2600     0    1.0    NaN    8.0  10065
28   1900     1    1.0    NaN    NaN  10065
291  2595     1    1.0    NaN    NaN  10065
259  2495     0    1.0    NaN    NaN  10065
261  2200     0    1.0  425.0    3.0  10075
283  2800     1    1.0  650.0    2.0  10075
310  1800     0    1.0    NaN    5.0  10075
307  2450     1    1.0    NaN    3.0  10075
163  2955     0    1.0    NaN    NaN  10280
50   2550     0    1.0  515.0    5.0  10280
201  2995     1    1.0  602.0    4.0  10280
69   2730     0    1.0  483.0    5.0  10280
246  2545     0    1.0  620.0   14.0  10280
190  2950     1    1.0  550.0    6.0  10280
220  2595     1    1.0    NaN    NaN  11229
14   3000     0    1.0  487.0    NaN    NaN
45   2950     0    1.0    NaN    NaN    NaN
249  2720     0    1.0  572.0    NaN    NaN
252  2940     0    1.0  280.0    NaN    NaN
253  2945     0    1.0  412.0    NaN    NaN
255  2500     0    1.0    NaN    NaN    NaN
258  2925     0    1.0  440.0    NaN    NaN
274  2620     0    1.0  421.0    NaN    NaN
302  2885     0    1.0  432.0    NaN    NaN
312  2950     0    1.0    NaN    NaN    NaN
313  2950     0    1.0    NaN    NaN    NaN
316  2965     0    1.0  522.0    NaN    NaN
317  2815     0    1.0  480.0    NaN    NaN

[275 rows x 6 columns]

In [62]:
import patsy
import statsmodels.api as sm

# 该行描述输入输出变量之间的关系：我们想知道邮政编码和w卧室数量将如何影响出租价格
f = 'Rent ~ Zip + Beds' 
# 传入公式和数据，输出X矩阵由预测变量组成，y向量由响应变量组成
y, X = patsy.dmatrices(f, su_lt_two, return_type='dataframe')

/Users/palance/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [63]:
results = sm.OLS(y, X).fit() # 运行模型
print(results.summary())     # 打印模型结果

                            OLS Regression Results
==============================================================================
Dep. Variable:                   Rent   R-squared:                       0.377
Model:                            OLS   Adj. R-squared:                  0.283
Method:                 Least Squares   F-statistic:                     4.034
Date:                Tue, 02 Jan 2018   Prob (F-statistic):           1.21e-10
Time:                        19:54:40   Log-Likelihood:                -1856.8
No. Observations:                 262   AIC:                             3784.
Df Residuals:                     227   BIC:                             3908.
Df Model:                          34
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     2737.5000    219.893     12.449      0.000    2304.207    3170.793
Zip[T.10002]  -503.2729    226.072     -2.226      0.027    -948.740     -57.806
Zip[T.10003]  -519.1638    230.290     -2.254      0.025    -972.943     -65.384
Zip[T.10004]    29.8051    260.334      0.114      0.909    -483.175     542.785
Zip[T.10005]  -221.5000    269.313     -0.822      0.412    -752.174     309.174
Zip[T.10006]  -132.7949    260.334     -0.510      0.610    -645.775     380.185
Zip[T.10009]  -416.4142    227.231     -1.833      0.068    -864.166      31.338
Zip[T.10010]  -646.9746    383.461     -1.687      0.093   -1402.572     108.623
Zip[T.10011]     4.3813    269.543      0.016      0.987    -526.746     535.508
Zip[T.10012]  -197.7638    235.233     -0.841      0.401    -661.283     265.755
Zip[T.10013]  -215.7045    234.573     -0.920      0.359    -677.924     246.515
Zip[T.10014]  -287.5000    380.867     -0.755      0.451   -1037.986     462.986
Zip[T.10016]  -215.8687    269.543     -0.801      0.424    -746.996     315.258
Zip[T.10017]  -212.6413    287.352     -0.740      0.460    -778.860     353.577
Zip[T.10019]  -348.8560    271.376     -1.286      0.200    -883.594     185.882
Zip[T.10021]  -627.6060    271.376     -2.313      0.022   -1162.344     -92.868
Zip[T.10022]  -567.5000    380.867     -1.490      0.138   -1317.986     182.986
Zip[T.10023]  -372.5707    254.885     -1.462      0.145    -874.814     129.673
Zip[T.10024]  -392.3687    246.100     -1.594      0.112    -877.302      92.564
Zip[T.10025]  -237.5000    380.867     -0.624      0.534    -987.986     512.986
Zip[T.10026]  -145.9746    314.148     -0.465      0.643    -764.994     473.045
Zip[T.10027] -1095.9746    314.148     -3.489      0.001   -1714.994    -476.955
Zip[T.10028]  -622.5848    261.550     -2.380      0.018   -1137.960    -107.209
Zip[T.10029]  -945.6498    255.640     -3.699      0.000   -1449.382    -441.918
Zip[T.10033] -1120.9746    383.461     -2.923      0.004   -1876.572    -365.377
Zip[T.10035]  -983.8560    271.376     -3.625      0.000   -1518.594    -449.118
Zip[T.10036]  -321.4831    285.429     -1.126      0.261    -883.912     240.946
Zip[T.10037] -1130.9746    314.148     -3.600      0.000   -1749.994    -511.955
Zip[T.10038]  -176.8475    240.922     -0.734      0.464    -651.578     297.883
Zip[T.10040] -1395.9746    383.461     -3.640      0.000   -2151.572    -640.377
Zip[T.10065]  -564.5848    261.550     -2.159      0.032   -1079.960     -49.209
Zip[T.10075]  -529.2373    270.232     -1.958      0.051   -1061.721       3.247
Zip[T.10280]   -19.4915    254.345     -0.077      0.939    -520.670     481.687
Zip[T.11229]  -350.9746    383.461     -0.915      0.361   -1106.572     404.623
Beds           208.4746     44.528      4.682      0.000     120.734     296.215
==============================================================================
Omnibus:                        3.745   Durbin-Watson:                   2.039
Prob(Omnibus):                  0.154   Jarque-Bera (JB):                2.546
Skew:                          -0.012   Prob(JB):                        0.280
Kurtosis:                       2.518   Cond. No.                         84.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## 预测

In [65]:
X.head()

,Intercept,Zip[T.10002],Zip[T.10003],Zip[T.10004],Zip[T.10005],Zip[T.10006],Zip[T.10009],Zip[T.10010],Zip[T.10011],Zip[T.10012],Zip[T.10013],Zip[T.10014],Zip[T.10016],Zip[T.10017],Zip[T.10019],...,Zip[T.10026],Zip[T.10027],Zip[T.10028],Zip[T.10029],Zip[T.10033],Zip[T.10035],Zip[T.10036],Zip[T.10037],Zip[T.10038],Zip[T.10040],Zip[T.10065],Zip[T.10075],Zip[T.10280],Zip[T.11229],Beds
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
results.params

Intercept       2737.500
Zip[T.10002]    -503.273
Zip[T.10003]    -519.164
Zip[T.10004]      29.805
Zip[T.10005]    -221.500
Zip[T.10006]    -132.795
Zip[T.10009]    -416.414
Zip[T.10010]    -646.975
Zip[T.10011]       4.381
Zip[T.10012]    -197.764
Zip[T.10013]    -215.704
Zip[T.10014]    -287.500
Zip[T.10016]    -215.869
Zip[T.10017]    -212.641
Zip[T.10019]    -348.856
Zip[T.10021]    -627.606
Zip[T.10022]    -567.500
Zip[T.10023]    -372.571
Zip[T.10024]    -392.369
Zip[T.10025]    -237.500
Zip[T.10026]    -145.975
Zip[T.10027]   -1095.975
Zip[T.10028]    -622.585
Zip[T.10029]    -945.650
Zip[T.10033]   -1120.975
Zip[T.10035]    -983.856
Zip[T.10036]    -321.483
Zip[T.10037]   -1130.975
Zip[T.10038]    -176.847
Zip[T.10040]   -1395.975
Zip[T.10065]    -564.585
Zip[T.10075]    -529.237
Zip[T.10280]     -19.492
Zip[T.11229]    -350.975
Beds             208.475
dtype: float64

In [67]:
to_pred_idx = X.iloc[0].index
to_pred_zeros = np.zeros(len(to_pred_idx))
tpdf = pd.DataFrame(to_pred_zeros, index=to_pred_idx, columns=['value'])

In [72]:
to_pred_idx

Index(['Intercept', 'Zip[T.10002]', 'Zip[T.10003]', 'Zip[T.10004]',
       'Zip[T.10005]', 'Zip[T.10006]', 'Zip[T.10009]', 'Zip[T.10010]',
       'Zip[T.10011]', 'Zip[T.10012]', 'Zip[T.10013]', 'Zip[T.10014]',
       'Zip[T.10016]', 'Zip[T.10017]', 'Zip[T.10019]', 'Zip[T.10021]',
       'Zip[T.10022]', 'Zip[T.10023]', 'Zip[T.10024]', 'Zip[T.10025]',
       'Zip[T.10026]', 'Zip[T.10027]', 'Zip[T.10028]', 'Zip[T.10029]',
       'Zip[T.10033]', 'Zip[T.10035]', 'Zip[T.10036]', 'Zip[T.10037]',
       'Zip[T.10038]', 'Zip[T.10040]', 'Zip[T.10065]', 'Zip[T.10075]',
       'Zip[T.10280]', 'Zip[T.11229]', 'Beds'],
      dtype='object')

In [68]:
tpdf

              value
Intercept       0.0
Zip[T.10002]    0.0
Zip[T.10003]    0.0
Zip[T.10004]    0.0
Zip[T.10005]    0.0
Zip[T.10006]    0.0
Zip[T.10009]    0.0
Zip[T.10010]    0.0
Zip[T.10011]    0.0
Zip[T.10012]    0.0
Zip[T.10013]    0.0
Zip[T.10014]    0.0
Zip[T.10016]    0.0
Zip[T.10017]    0.0
Zip[T.10019]    0.0
Zip[T.10021]    0.0
Zip[T.10022]    0.0
Zip[T.10023]    0.0
Zip[T.10024]    0.0
Zip[T.10025]    0.0
Zip[T.10026]    0.0
Zip[T.10027]    0.0
Zip[T.10028]    0.0
Zip[T.10029]    0.0
Zip[T.10033]    0.0
Zip[T.10035]    0.0
Zip[T.10036]    0.0
Zip[T.10037]    0.0
Zip[T.10038]    0.0
Zip[T.10040]    0.0
Zip[T.10065]    0.0
Zip[T.10075]    0.0
Zip[T.10280]    0.0
Zip[T.11229]    0.0
Beds            0.0

In [69]:
tpdf['value'] = 0
tpdf.loc['Intercept'] = 1
tpdf.loc['Beds'] = 2
tpdf.loc['Zip[T.10002]'] = 1

In [70]:
tpdf

              value
Intercept         1
Zip[T.10002]      1
Zip[T.10003]      0
Zip[T.10004]      0
Zip[T.10005]      0
Zip[T.10006]      0
Zip[T.10009]      0
Zip[T.10010]      0
Zip[T.10011]      0
Zip[T.10012]      0
Zip[T.10013]      0
Zip[T.10014]      0
Zip[T.10016]      0
Zip[T.10017]      0
Zip[T.10019]      0
Zip[T.10021]      0
Zip[T.10022]      0
Zip[T.10023]      0
Zip[T.10024]      0
Zip[T.10025]      0
Zip[T.10026]      0
Zip[T.10027]      0
Zip[T.10028]      0
Zip[T.10029]      0
Zip[T.10033]      0
Zip[T.10035]      0
Zip[T.10036]      0
Zip[T.10037]      0
Zip[T.10038]      0
Zip[T.10040]      0
Zip[T.10065]      0
Zip[T.10075]      0
Zip[T.10280]      0
Zip[T.11229]      0
Beds              2

In [71]:
results.predict(tpdf['value'])

Intercept       2651.176
Zip[T.10002]    2651.176
Zip[T.10003]    2651.176
Zip[T.10004]    2651.176
Zip[T.10005]    2651.176
Zip[T.10006]    2651.176
Zip[T.10009]    2651.176
Zip[T.10010]    2651.176
Zip[T.10011]    2651.176
Zip[T.10012]    2651.176
Zip[T.10013]    2651.176
Zip[T.10014]    2651.176
Zip[T.10016]    2651.176
Zip[T.10017]    2651.176
Zip[T.10019]    2651.176
Zip[T.10021]    2651.176
Zip[T.10022]    2651.176
Zip[T.10023]    2651.176
Zip[T.10024]    2651.176
Zip[T.10025]    2651.176
Zip[T.10026]    2651.176
Zip[T.10027]    2651.176
Zip[T.10028]    2651.176
Zip[T.10029]    2651.176
Zip[T.10033]    2651.176
Zip[T.10035]    2651.176
Zip[T.10036]    2651.176
Zip[T.10037]    2651.176
Zip[T.10038]    2651.176
Zip[T.10040]    2651.176
Zip[T.10065]    2651.176
Zip[T.10075]    2651.176
Zip[T.10280]    2651.176
Zip[T.11229]    2651.176
Beds            2651.176
dtype: float64